//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data.Objects;
using System.Linq;
using System.Linq.Expressions;
using CPC.POSReport.Database;

namespace CPC.POSReport.Repository
{
    /// <summary>
    /// Repository for table base_CardManagement 
    /// </summary>
    public partial class base_CardManagementRepository
    {
        #region Auto Generate Code

        #region Constructors

        // Default constructor
        public base_CardManagementRepository()
        {
        }

        #endregion

        #region Basic C.R.U.D. Operations

        /// <summary>
        /// Add new base_CardManagement.
        /// </summary>
        /// <param name="base_CardManagement">base_CardManagement to add.</param>
        /// <returns>base_CardManagement have been added.</returns>
        public base_CardManagement Add(base_CardManagement base_CardManagement)
        {
            UnitOfWork.Add<base_CardManagement>(base_CardManagement);
            return base_CardManagement;
        }

        /// <summary>
        /// Adds a sequence of new base_CardManagement.
        /// </summary>
        /// <param name="base_CardManagement">Sequence of new base_CardManagement to add.</param>
        /// <returns>Sequence of new base_CardManagement have been added.</returns>
        public IEnumerable<base_CardManagement> Add(IEnumerable<base_CardManagement> base_CardManagement)
        {
            UnitOfWork.Add<base_CardManagement>(base_CardManagement);
            return base_CardManagement;
        }

        /// <summary>
        /// Delete a existed base_CardManagement.
        /// </summary>
        /// <param name="base_CardManagement">base_CardManagement to delete.</param>
        public void Delete(base_CardManagement base_CardManagement)
        {
            Refresh(base_CardManagement);
            if (base_CardManagement.EntityState != System.Data.EntityState.Detached)
                UnitOfWork.Delete<base_CardManagement>(base_CardManagement);
        }

        /// <summary>
        /// Delete a sequence of existed base_CardManagement.
        /// </summary>
        /// <param name="base_CardManagement">Sequence of existed base_CardManagement to delete.</param>
        public void Delete(IEnumerable<base_CardManagement> base_CardManagement)
        {
            int total = base_CardManagement.Count();
            for (int i = total - 1; i >= 0; i--)
                Delete(base_CardManagement.ElementAt(i));
        }

        /// <summary>
        /// Returns the first base_CardManagement of a sequence that satisfies a specified condition or 
        /// a default value if no such base_CardManagement is found.
        /// </summary>
        /// <param name="expression">A function to test each base_CardManagement for a condition.</param>
        /// <returns>    
        /// Null if source is empty or if no base_CardManagement passes the test specified by expression; 
        /// otherwise, the first base_CardManagement in source that passes the test specified by expression.
        /// </returns>
        public base_CardManagement Get(Expression<Func<base_CardManagement, bool>> expression)
        {
            return UnitOfWork.Get<base_CardManagement>(expression);
        }

        /// <summary>
        /// Get all base_CardManagement.
        /// </summary>
        /// <returns>The new IList&lt;base_CardManagement&gt; instance.</returns>
        public IList<base_CardManagement> GetAll()
        {
            return UnitOfWork.GetAll<base_CardManagement>().ToList();
        }

        /// <summary>
        /// Get all base_CardManagement that satisfies a specified condition.
        /// </summary>
        /// <param name="expression">A function to test each base_CardManagement for a condition.</param>
        /// <returns>The new IList&lt;base_CardManagement&gt; instance.</returns>
        public IList<base_CardManagement> GetAll(Expression<Func<base_CardManagement, bool>> expression)
        {
            return UnitOfWork.GetAll<base_CardManagement>(expression).ToList();
        }

        /// <summary>
        /// Get all base_CardManagement.
        /// </summary>
        /// <returns>The new IEnumerable&lt;base_CardManagement&gt; instance.</returns>
        public IEnumerable<base_CardManagement> GetIEnumerable()
        {
            return UnitOfWork.GetIEnumerable<base_CardManagement>();
        }

        /// <summary>
        /// Get all base_CardManagement that satisfies a specified condition.
        /// </summary>
        /// <param name="expression">A function to test each base_CardManagement for a condition.</param>
        /// <returns>The new IEnumerable&lt;base_CardManagement&gt; instance.</returns>
        public IEnumerable<base_CardManagement> GetIEnumerable(Expression<Func<base_CardManagement, bool>> expression)
        {
            return UnitOfWork.GetIEnumerable<base_CardManagement>(expression);
        }

        /// <summary>
        /// Get all base_CardManagement.
        /// </summary>
        /// <returns>The new IQueryable&lt;base_CardManagement&gt; instance.</returns>
        public IQueryable<base_CardManagement> GetIQueryable()
        {
            return UnitOfWork.GetIQueryable<base_CardManagement>();
        }

        /// <summary>
        /// Get all base_CardManagement that satisfies a specified condition.
        /// </summary>
        /// <param name="expression">A function to test each base_CardManagement for a condition.</param>
        /// <returns>The new IQueryable&lt;base_CardManagement&gt; instance.</returns>
        public IQueryable<base_CardManagement> GetIQueryable(Expression<Func<base_CardManagement, bool>> expression)
        {
            return UnitOfWork.GetIQueryable<base_CardManagement>(expression);
        }

        /// <summary>
        /// Take a few base_CardManagement in a sequence was sorted on server.
        /// </summary>
        /// <param name="ignoreCount">Number of base_CardManagement will ignore.</param>
        /// <param name="takeCount">Number of base_CardManagement will take.</param>
        /// <param name="keys">The key columns by which to order the results.</param>
        /// <returns>The new IList&lt;base_CardManagement&gt; instance.</returns>
        public IList<base_CardManagement> GetRange(int ignoreCount, int takeCount, string keys)
        {
            return UnitOfWork.GetRange<base_CardManagement>(ignoreCount, takeCount, keys);
        }

        /// <summary>
        /// Take a few base_CardManagement in a sequence was sorted on server.
        /// </summary>
        /// <param name="ignoreCount">Number of base_CardManagement will ignore.</param>
        /// <param name="takeCount">Number of base_CardManagement will take.</param>
        /// <param name="keys">The key columns by which to order the results.</param>
        /// <param name="expression">A function to test each base_CardManagement for a condition.</param>
        /// <returns>The new IList&lt;base_CardManagement&gt; instance.</returns>
        public IList<base_CardManagement> GetRange(int ignoreCount, int takeCount, string keys, Expression<Func<base_CardManagement, bool>> expression)
        {
            return UnitOfWork.GetRange<base_CardManagement>(ignoreCount, takeCount, keys, expression);
        }

        /// <summary>
        /// Updates an base_CardManagement in the object context with data from the data source.
        /// </summary>
        /// <param name="base_CardManagement">The base_CardManagement to be refreshed.</param>
        public base_CardManagement Refresh(base_CardManagement base_CardManagement)
        {
            UnitOfWork.Refresh<base_CardManagement>(base_CardManagement);
            if (base_CardManagement.EntityState != System.Data.EntityState.Detached)
                return base_CardManagement;
            return null;
        }

        /// <summary>
        /// Updates a sequence of base_CardManagement in the object context with data from the data source.
        /// </summary>
        /// <typeparam name="base_CardManagement">Type of object in a sequence to refresh.</typeparam>
        /// <param name="base_CardManagement">Object collection to be refreshed.</param>
        public void Refresh(IEnumerable<base_CardManagement> base_CardManagement)
        {
            UnitOfWork.Refresh<base_CardManagement>(base_CardManagement);
        }

        /// <summary>
        /// Updates a sequence of base_CardManagement in the object context with data from the data source.
        /// </summary>
        public void Refresh()
        {
            UnitOfWork.Refresh<base_CardManagement>();
        }

        /// <summary>
        /// Persists all updates to the data source and resets change tracking in the object context.
        /// </summary>
        public void Commit()
        {
            UnitOfWork.Commit();
        }

        /// <summary>
        /// Persists all updates to the data source with the specified System.Data.Objects.SaveOptions.
        /// </summary>
        /// <param name="options">A System.Data.Objects.SaveOptions value that determines the behavior of the operation.</param>
        public void Commit(SaveOptions options)
        {
            UnitOfWork.Commit(options);
        }

        /// <summary>
        /// Starts a database transaction.
        /// </summary>
        public void BeginTransaction()
        {
            UnitOfWork.BeginTransaction();
        }

        /// <summary>
        /// Commits the database transaction.
        /// </summary>
        public void CommitTransaction()
        {
            UnitOfWork.CommitTransaction();
        }

        /// <summary>
        /// Rolls back a transaction from a pending state.
        /// </summary>
        public void RollbackTransaction()
        {
            UnitOfWork.RollbackTransaction();
        }

        #endregion

        #endregion

        #region Custom Code


        #endregion
    }
}
