//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data.Objects;
using System.Linq;
using System.Linq.Expressions;
using CPC.POSReport.Database;

namespace CPC.POSReport.Repository
{
    /// <summary>
    /// Repository for table base_SaleTaxLocationOption 
    /// </summary>
    public partial class base_SaleTaxLocationOptionRepository
    {
        #region Auto Generate Code

        #region Constructors

        // Default constructor
        public base_SaleTaxLocationOptionRepository()
        {
        }

        #endregion

        #region Basic C.R.U.D. Operations

        /// <summary>
        /// Add new base_SaleTaxLocationOption.
        /// </summary>
        /// <param name="base_SaleTaxLocationOption">base_SaleTaxLocationOption to add.</param>
        /// <returns>base_SaleTaxLocationOption have been added.</returns>
        public base_SaleTaxLocationOption Add(base_SaleTaxLocationOption base_SaleTaxLocationOption)
        {
            UnitOfWork.Add<base_SaleTaxLocationOption>(base_SaleTaxLocationOption);
            return base_SaleTaxLocationOption;
        }

        /// <summary>
        /// Adds a sequence of new base_SaleTaxLocationOption.
        /// </summary>
        /// <param name="base_SaleTaxLocationOption">Sequence of new base_SaleTaxLocationOption to add.</param>
        /// <returns>Sequence of new base_SaleTaxLocationOption have been added.</returns>
        public IEnumerable<base_SaleTaxLocationOption> Add(IEnumerable<base_SaleTaxLocationOption> base_SaleTaxLocationOption)
        {
            UnitOfWork.Add<base_SaleTaxLocationOption>(base_SaleTaxLocationOption);
            return base_SaleTaxLocationOption;
        }

        /// <summary>
        /// Delete a existed base_SaleTaxLocationOption.
        /// </summary>
        /// <param name="base_SaleTaxLocationOption">base_SaleTaxLocationOption to delete.</param>
        public void Delete(base_SaleTaxLocationOption base_SaleTaxLocationOption)
        {
            Refresh(base_SaleTaxLocationOption);
            if (base_SaleTaxLocationOption.EntityState != System.Data.EntityState.Detached)
                UnitOfWork.Delete<base_SaleTaxLocationOption>(base_SaleTaxLocationOption);
        }

        /// <summary>
        /// Delete a sequence of existed base_SaleTaxLocationOption.
        /// </summary>
        /// <param name="base_SaleTaxLocationOption">Sequence of existed base_SaleTaxLocationOption to delete.</param>
        public void Delete(IEnumerable<base_SaleTaxLocationOption> base_SaleTaxLocationOption)
        {
            int total = base_SaleTaxLocationOption.Count();
            for (int i = total - 1; i >= 0; i--)
                Delete(base_SaleTaxLocationOption.ElementAt(i));
        }

        /// <summary>
        /// Returns the first base_SaleTaxLocationOption of a sequence that satisfies a specified condition or 
        /// a default value if no such base_SaleTaxLocationOption is found.
        /// </summary>
        /// <param name="expression">A function to test each base_SaleTaxLocationOption for a condition.</param>
        /// <returns>    
        /// Null if source is empty or if no base_SaleTaxLocationOption passes the test specified by expression; 
        /// otherwise, the first base_SaleTaxLocationOption in source that passes the test specified by expression.
        /// </returns>
        public base_SaleTaxLocationOption Get(Expression<Func<base_SaleTaxLocationOption, bool>> expression)
        {
            return UnitOfWork.Get<base_SaleTaxLocationOption>(expression);
        }

        /// <summary>
        /// Get all base_SaleTaxLocationOption.
        /// </summary>
        /// <returns>The new IList&lt;base_SaleTaxLocationOption&gt; instance.</returns>
        public IList<base_SaleTaxLocationOption> GetAll()
        {
            return UnitOfWork.GetAll<base_SaleTaxLocationOption>().ToList();
        }

        /// <summary>
        /// Get all base_SaleTaxLocationOption that satisfies a specified condition.
        /// </summary>
        /// <param name="expression">A function to test each base_SaleTaxLocationOption for a condition.</param>
        /// <returns>The new IList&lt;base_SaleTaxLocationOption&gt; instance.</returns>
        public IList<base_SaleTaxLocationOption> GetAll(Expression<Func<base_SaleTaxLocationOption, bool>> expression)
        {
            return UnitOfWork.GetAll<base_SaleTaxLocationOption>(expression).ToList();
        }

        /// <summary>
        /// Get all base_SaleTaxLocationOption.
        /// </summary>
        /// <returns>The new IEnumerable&lt;base_SaleTaxLocationOption&gt; instance.</returns>
        public IEnumerable<base_SaleTaxLocationOption> GetIEnumerable()
        {
            return UnitOfWork.GetIEnumerable<base_SaleTaxLocationOption>();
        }

        /// <summary>
        /// Get all base_SaleTaxLocationOption that satisfies a specified condition.
        /// </summary>
        /// <param name="expression">A function to test each base_SaleTaxLocationOption for a condition.</param>
        /// <returns>The new IEnumerable&lt;base_SaleTaxLocationOption&gt; instance.</returns>
        public IEnumerable<base_SaleTaxLocationOption> GetIEnumerable(Expression<Func<base_SaleTaxLocationOption, bool>> expression)
        {
            return UnitOfWork.GetIEnumerable<base_SaleTaxLocationOption>(expression);
        }

        /// <summary>
        /// Get all base_SaleTaxLocationOption.
        /// </summary>
        /// <returns>The new IQueryable&lt;base_SaleTaxLocationOption&gt; instance.</returns>
        public IQueryable<base_SaleTaxLocationOption> GetIQueryable()
        {
            return UnitOfWork.GetIQueryable<base_SaleTaxLocationOption>();
        }

        /// <summary>
        /// Get all base_SaleTaxLocationOption that satisfies a specified condition.
        /// </summary>
        /// <param name="expression">A function to test each base_SaleTaxLocationOption for a condition.</param>
        /// <returns>The new IQueryable&lt;base_SaleTaxLocationOption&gt; instance.</returns>
        public IQueryable<base_SaleTaxLocationOption> GetIQueryable(Expression<Func<base_SaleTaxLocationOption, bool>> expression)
        {
            return UnitOfWork.GetIQueryable<base_SaleTaxLocationOption>(expression);
        }

        /// <summary>
        /// Take a few base_SaleTaxLocationOption in a sequence was sorted on server.
        /// </summary>
        /// <param name="ignoreCount">Number of base_SaleTaxLocationOption will ignore.</param>
        /// <param name="takeCount">Number of base_SaleTaxLocationOption will take.</param>
        /// <param name="keys">The key columns by which to order the results.</param>
        /// <returns>The new IList&lt;base_SaleTaxLocationOption&gt; instance.</returns>
        public IList<base_SaleTaxLocationOption> GetRange(int ignoreCount, int takeCount, string keys)
        {
            return UnitOfWork.GetRange<base_SaleTaxLocationOption>(ignoreCount, takeCount, keys);
        }

        /// <summary>
        /// Take a few base_SaleTaxLocationOption in a sequence was sorted on server.
        /// </summary>
        /// <param name="ignoreCount">Number of base_SaleTaxLocationOption will ignore.</param>
        /// <param name="takeCount">Number of base_SaleTaxLocationOption will take.</param>
        /// <param name="keys">The key columns by which to order the results.</param>
        /// <param name="expression">A function to test each base_SaleTaxLocationOption for a condition.</param>
        /// <returns>The new IList&lt;base_SaleTaxLocationOption&gt; instance.</returns>
        public IList<base_SaleTaxLocationOption> GetRange(int ignoreCount, int takeCount, string keys, Expression<Func<base_SaleTaxLocationOption, bool>> expression)
        {
            return UnitOfWork.GetRange<base_SaleTaxLocationOption>(ignoreCount, takeCount, keys, expression);
        }

        /// <summary>
        /// Updates an base_SaleTaxLocationOption in the object context with data from the data source.
        /// </summary>
        /// <param name="base_SaleTaxLocationOption">The base_SaleTaxLocationOption to be refreshed.</param>
        public base_SaleTaxLocationOption Refresh(base_SaleTaxLocationOption base_SaleTaxLocationOption)
        {
            UnitOfWork.Refresh<base_SaleTaxLocationOption>(base_SaleTaxLocationOption);
            if (base_SaleTaxLocationOption.EntityState != System.Data.EntityState.Detached)
                return base_SaleTaxLocationOption;
            return null;
        }

        /// <summary>
        /// Updates a sequence of base_SaleTaxLocationOption in the object context with data from the data source.
        /// </summary>
        /// <typeparam name="base_SaleTaxLocationOption">Type of object in a sequence to refresh.</typeparam>
        /// <param name="base_SaleTaxLocationOption">Object collection to be refreshed.</param>
        public void Refresh(IEnumerable<base_SaleTaxLocationOption> base_SaleTaxLocationOption)
        {
            UnitOfWork.Refresh<base_SaleTaxLocationOption>(base_SaleTaxLocationOption);
        }

        /// <summary>
        /// Updates a sequence of base_SaleTaxLocationOption in the object context with data from the data source.
        /// </summary>
        public void Refresh()
        {
            UnitOfWork.Refresh<base_SaleTaxLocationOption>();
        }

        /// <summary>
        /// Persists all updates to the data source and resets change tracking in the object context.
        /// </summary>
        public void Commit()
        {
            UnitOfWork.Commit();
        }

        /// <summary>
        /// Persists all updates to the data source with the specified System.Data.Objects.SaveOptions.
        /// </summary>
        /// <param name="options">A System.Data.Objects.SaveOptions value that determines the behavior of the operation.</param>
        public void Commit(SaveOptions options)
        {
            UnitOfWork.Commit(options);
        }

        /// <summary>
        /// Starts a database transaction.
        /// </summary>
        public void BeginTransaction()
        {
            UnitOfWork.BeginTransaction();
        }

        /// <summary>
        /// Commits the database transaction.
        /// </summary>
        public void CommitTransaction()
        {
            UnitOfWork.CommitTransaction();
        }

        /// <summary>
        /// Rolls back a transaction from a pending state.
        /// </summary>
        public void RollbackTransaction()
        {
            UnitOfWork.RollbackTransaction();
        }

        #endregion

        #endregion

        #region Custom Code


        #endregion
    }
}
