//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using CPC.POS.Database;
using CPC.Toolkit.Base;

namespace CPC.POS.Model
{
    /// <summary>
    /// Model for table base_CountStockDetail
    /// </summary>
    [Serializable]
    public partial class base_CountStockDetailModel : ModelBase, IDataErrorInfo
    {
        #region Constructor

        // Default constructor
        public base_CountStockDetailModel()
        {
            this.IsNew = true;
            this.base_CountStockDetail = new base_CountStockDetail();
        }

        // Default constructor that set entity to field
        public base_CountStockDetailModel(base_CountStockDetail base_countstockdetail, bool isRaiseProperties = false)
        {
            this.base_CountStockDetail = base_countstockdetail;
            if (!isRaiseProperties)
                this.ToModel();
            else
                this.ToModelAndRaise();
            this.IsDirty = false;
        }

        #endregion

        #region Entity Properties

        public base_CountStockDetail base_CountStockDetail { get; private set; }

        #endregion

        #region Primitive Properties

        protected long _id;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Id</para>
        /// </summary>
        public long Id
        {
            get { return this._id; }
            set
            {
                if (this._id != value)
                {
                    this.IsDirty = true;
                    this._id = value;
                    OnPropertyChanged(() => Id);
                    PropertyChangedCompleted(() => Id);
                }
            }
        }

        protected long _countStockId;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the CountStockId</para>
        /// </summary>
        public long CountStockId
        {
            get { return this._countStockId; }
            set
            {
                if (this._countStockId != value)
                {
                    this.IsDirty = true;
                    this._countStockId = value;
                    OnPropertyChanged(() => CountStockId);
                    PropertyChangedCompleted(() => CountStockId);
                }
            }
        }

        protected long _productId;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the ProductId</para>
        /// </summary>
        public long ProductId
        {
            get { return this._productId; }
            set
            {
                if (this._productId != value)
                {
                    this.IsDirty = true;
                    this._productId = value;
                    OnPropertyChanged(() => ProductId);
                    PropertyChangedCompleted(() => ProductId);
                }
            }
        }

        protected string _productResource;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the ProductResource</para>
        /// </summary>
        public string ProductResource
        {
            get { return this._productResource; }
            set
            {
                if (this._productResource != value)
                {
                    this.IsDirty = true;
                    this._productResource = value;
                    OnPropertyChanged(() => ProductResource);
                    PropertyChangedCompleted(() => ProductResource);
                }
            }
        }

        protected short _storeId;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the StoreId</para>
        /// </summary>
        public short StoreId
        {
            get { return this._storeId; }
            set
            {
                if (this._storeId != value)
                {
                    this.IsDirty = true;
                    this._storeId = value;
                    OnPropertyChanged(() => StoreId);
                    PropertyChangedCompleted(() => StoreId);
                }
            }
        }

        protected int _quantity;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Quantity</para>
        /// </summary>
        public int Quantity
        {
            get { return this._quantity; }
            set
            {
                if (this._quantity != value)
                {
                    this.IsDirty = true;
                    this._quantity = value;
                    OnPropertyChanged(() => Quantity);
                    PropertyChangedCompleted(() => Quantity);
                }
            }
        }

        protected int _countedQuantity;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the CountedQuantity</para>
        /// </summary>
        public int CountedQuantity
        {
            get { return this._countedQuantity; }
            set
            {
                if (this._countedQuantity != value)
                {
                    this.IsDirty = true;
                    this._countedQuantity = value;
                    OnPropertyChanged(() => CountedQuantity);
                    PropertyChangedCompleted(() => CountedQuantity);
                }
            }
        }

        #endregion

        #region Public Methods

        /// <summary>
        /// <para>Public Method</para>
        /// Method for set IsNew & IsDirty = false;
        /// </summary>
        public void EndUpdate()
        {
            this.IsNew = false;
            this.IsDirty = false;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set PropertyModel to Entity</para>
        /// </summary>
        public void ToEntity()
        {
            if (IsNew)
                this.base_CountStockDetail.Id = this.Id;
            this.base_CountStockDetail.CountStockId = this.CountStockId;
            this.base_CountStockDetail.ProductId = this.ProductId;
            this.base_CountStockDetail.ProductResource = this.ProductResource;
            this.base_CountStockDetail.StoreId = this.StoreId;
            this.base_CountStockDetail.Quantity = this.Quantity;
            this.base_CountStockDetail.CountedQuantity = this.CountedQuantity;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set Entity to PropertyModel</para>
        /// </summary
        public void ToModel()
        {
            this._id = this.base_CountStockDetail.Id;
            this._countStockId = this.base_CountStockDetail.CountStockId;
            this._productId = this.base_CountStockDetail.ProductId;
            this._productResource = this.base_CountStockDetail.ProductResource;
            this._storeId = this.base_CountStockDetail.StoreId;
            this._quantity = this.base_CountStockDetail.Quantity;
            this._countedQuantity = this.base_CountStockDetail.CountedQuantity;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set Entity to PropertyModel</para>
        /// </summary
        public void ToModelAndRaise()
        {
            this.Id = this.base_CountStockDetail.Id;
            this.CountStockId = this.base_CountStockDetail.CountStockId;
            this.ProductId = this.base_CountStockDetail.ProductId;
            this.ProductResource = this.base_CountStockDetail.ProductResource;
            this.StoreId = this.base_CountStockDetail.StoreId;
            this.Quantity = this.base_CountStockDetail.Quantity;
            this.CountedQuantity = this.base_CountStockDetail.CountedQuantity;
        }

        #endregion

        #region Custom Code
        protected string _productName;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the ProductName</para>
        /// </summary>
        public string ProductName
        {
            get { return this._productName; }
            set
            {
                if (this._productName != value)
                {
                    this._productName = value;
                    OnPropertyChanged(() => ProductName);
                    PropertyChangedCompleted(() => ProductName);
                }
            }
        }

        protected string _description;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Description</para>
        /// </summary>
        public string Description
        {
            get { return this._description; }
            set
            {
                if (this._description != value)
                {
                    this._description = value;
                    OnPropertyChanged(() => Description);
                    PropertyChangedCompleted(() => Description);
                }
            }
        }

        protected string _attribute;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Attribute</para>
        /// </summary>
        public string Attribute
        {
            get { return this._attribute; }
            set
            {
                if (this._attribute != value)
                {
                    this._attribute = value;
                    OnPropertyChanged(() => Attribute);
                    PropertyChangedCompleted(() => Attribute);
                }
            }
        }

        protected string _size;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Size</para>
        /// </summary>
        public string Size
        {
            get { return this._size; }
            set
            {
                if (this._size != value)
                {
                    this._size = value;
                    OnPropertyChanged(() => Size);
                    PropertyChangedCompleted(() => Size);
                }
            }
        }

        protected string _productCode;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the ProductResource</para>
        /// </summary>
        public string ProductCode
        {
            get { return this._productCode; }
            set
            {
                if (this._productCode != value)
                {
                    this._productCode = value;
                    OnPropertyChanged(() => ProductCode);
                }
            }
        }

        #endregion

        #region IDataErrorInfo Members

        public string Error
        {
            get
            {
                List<string> errors = new List<string>();
                PropertyDescriptorCollection props = TypeDescriptor.GetProperties(this);
                foreach (PropertyDescriptor prop in props)
                {
                    string msg = this[prop.Name];
                    if (!string.IsNullOrWhiteSpace(msg))
                    {
                        errors.Add(msg);
                    }
                }
                return string.Join(Environment.NewLine, errors);
            }
        }

        public string this[string columnName]
        {
            get
            {
                string message = string.Empty;

                switch (columnName)
                {
                    case "Id":
                        break;
                    case "CountStockId":
                        break;
                    case "ProductId":
                        break;
                    case "ProductResource":
                        break;
                    case "StoreId":
                        break;
                    case "Quantity":
                        break;
                    case "CountedQuantity":
                        break;
                }

                if (!string.IsNullOrWhiteSpace(message))
                    return message;
                return null;
            }
        }

        #endregion
    }
}
