//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using FlashCard.Models;
using FlashCard.Database;


namespace FlashCard.Database
{
    /// <summary>
    /// Model for table Card 
    /// </summary>
    public partial class CardModel : ViewModelBase
    {
        #region Ctor

        // Default contructor
        public CardModel()
        {
            this.IsNew = true;
            this.Card = new Card();
        }

        // Default contructor that set entity to field
        public CardModel(Card card)
        {
            this.Card = card;
        }

        #endregion

        #region Entity Properties

        public Card Card { get; private set; }

        public bool IsNew { get; private set; }
        public bool IsDirty { get; private set; }
        public bool Deleted { get; set; }
        public bool Checked { get; set; }

        public void EndUpdate()
        {
            IsNew = false;
            IsDirty = false;
        }


        #endregion

        #region Primitive Properties


        private string _cardID = string.Empty;
        public string CardID
        {
            get
            {
                return _cardID;
            }
            //get { return this.Card.CardID; }
            set
            {
                if (_cardID != value)
                {
                    this.IsDirty = true;
                    //this.Card.CardID = value;
                    _cardID = value;
                    RaisePropertyChanged(() => CardID);
                }
            }
        }
        private string _cardName = string.Empty;

        public string CardName
        {
            get {
             
                return _cardName; }
            //get { return this.Card.CardName; }
            set
            {
                if (_cardName != value)
                {
                    this.IsDirty = true;
                    _cardName = value;
                    //this.Card.CardName = value;
                    RaisePropertyChanged(() => CardName);
                }
            }
        }

        private string _remark = string.Empty;
        public string Remark
        {
            get { return _remark; }
            //get { return this.Card.Remark; }
            set
            {
                if (_remark != value)
                {
                    this.IsDirty = true;
                    //this.Card.Remark = value;
                    _remark = value;
                    RaisePropertyChanged(() => Remark);
                }
            }
        }

        #endregion

        #region all the custom code
        public void ToEntity()
        {
            this.Card.CardID = CardID;
            this.Card.CardName = CardName;
            this.Card.Remark = Remark;
        }

        #endregion
    }
}
