//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using FlashCard.Models;
using System.Xml.Serialization;

namespace FlashCard.Database
{
    /// <summary>
    /// Model for table Lesson 
    /// </summary>
    public partial class LessonModel : ViewModelBase, IDataErrorInfo
    {
        #region Ctor

        // Default contructor
        public LessonModel()
        {
            this.IsNew = true;
            this.Lesson = new Lesson();
        }

        // Default contructor that set entity to field
        public LessonModel(Lesson lesson)
        {
            this.Lesson = lesson;
            ToModel();
            this.IsDirty = false;
        }

        #endregion

        #region Entity Properties
        [XmlIgnore]
        public Lesson Lesson { get; private set; }
        [XmlIgnore]
        protected bool _isNew;
        /// <summary>
        /// Property Base
        /// <para> Gets or sets the IsNew </para>
        /// </summary>
        /// 
        [XmlIgnore]
        public bool IsNew
        {
            get { return _isNew; }
            set
            {
                if (_isNew != value)
                {
                    _isNew = value;
                    RaisePropertyChanged(() => IsNew);
                }
            }
        }


        protected bool _isDirty;
        /// <summary>
        /// Property Base
        /// <para>Gets or sets the IsDirty</para>
        /// </summary>
        /// 
        [XmlIgnore]
        public bool IsDirty
        {
            get { return _isDirty; }
            set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    RaisePropertyChanged(() => IsDirty);
                }
            }
        }

        protected bool _isDeleted;
        /// <summary>
        /// Property Base
        ///<para>Gets or sets the IsDeleted</para>
        /// </summary>
        /// 
        [XmlIgnore]
        public bool IsDeleted
        {
            get { return _isDeleted; }
            set
            {
                if (_isDeleted != value)
                {
                    _isDeleted = value;
                    RaisePropertyChanged(() => IsDeleted);
                }
            }
        }

        protected bool _isChecked;
        /// <summary>
        /// Property Base
        ///<para> Gets or sets the IsChecked</para>
        /// </summary>
        /// 
        [XmlIgnore]
        public bool IsChecked
        {
            get { return _isChecked; }
            set
            {
                if (_isChecked != value)
                {
                    _isChecked = value;
                    RaisePropertyChanged(() => IsChecked);
                }
            }
        }


        /// <summary>
        ///<para>Public Method</para>
        /// Method for set IsNew & IsDirty = false;
        /// </summary>
        public void EndUpdate()
        {
            this.IsNew = false;
            this.IsDirty = false;
        }

        /// <summary>
        ///Public Method
        ///<para> Method for set PropertyModel to Entity</para>
        /// </summary>
        public void ToEntity()
        {
            if (IsNew)
                this.Lesson.LessonID = this.LessonID;
            this.Lesson.LessonName = this.LessonName.Trim();
            this.Lesson.Description = this.Description.Trim();
            this.Lesson.CategoryID = this.CategoryID.Trim();
            this.Lesson.CardID = this.CardID.Trim();
        }


        /// <summary>
        ///Public Method
        ///<para> Method for set Entity to PropertyModel</para>
        /// </summary
        public void ToModel()
        {
            this.LessonID = this.Lesson.LessonID;
            this.LessonName = this.Lesson.LessonName;
            this.Description = this.Lesson.Description;
            this.CategoryID = this.Lesson.CategoryID;
            this.CardID = this.Lesson.CardID;
        }

        #endregion

        #region Primitive Properties

        protected string _lessonID;
        /// <summary>
        ///Property Model
        ///<para> Gets or sets the LessonID.</para>
        /// </summary>
        public string LessonID
        {
            get { return this._lessonID; }
            set
            {
                if (this._lessonID != value)
                {
                    this.IsDirty = true;
                    this._lessonID = value;
                    RaisePropertyChanged(() => LessonID);
                }
            }
        }

        protected string _lessonName;
        /// <summary>
        ///Property Model
        ///<para> Gets or sets the LessonName.</para>
        /// </summary>
        /// 
        public string LessonName
        {
            get { return this._lessonName; }
            set
            {
                if (this._lessonName != value)
                {
                    this.IsDirty = true;
                    this._lessonName = value;
                    RaisePropertyChanged(() => LessonName);
                }
            }
        }

        protected string _description;
        /// <summary>
        ///Property Model
        ///<para> Gets or sets the Description.</para>
        /// </summary>
        /// 
        public string Description
        {
            get { return this._description; }
            set
            {
                if (this._description != value)
                {
                    this.IsDirty = true;
                    this._description = value;
                    RaisePropertyChanged(() => Description);
                }
            }
        }

        protected string _categoryID;
        /// <summary>
        ///Property Model
        ///<para> Gets or sets the CategoryID.</para>
        /// </summary>
        /// 
        public string CategoryID
        {
            get { return this._categoryID; }
            set
            {
                if (this._categoryID != value)
                {
                    this.IsDirty = true;
                    this._categoryID = value;
                    RaisePropertyChanged(() => CategoryID);
                }
            }
        }

        protected string _cardID;
        /// <summary>
        ///Property Model
        ///<para> Gets or sets the CardID.</para>
        /// </summary>
        /// 
        public string CardID
        {
            get { return this._cardID; }
            set
            {
                if (this._cardID != value)
                {
                    this.IsDirty = true;
                    this._cardID = value;
                    RaisePropertyChanged(() => CardID);
                }
            }
        }


        #endregion

        #region Custom Code
        #region Properties
        private bool _isBackSide = false;
        /// <summary>
        /// This is Extend Properties
        ///<para> Gets or sets the property value.</para>
        /// </summary>
        /// 
        [XmlIgnore]
        public bool IsBackSide
        {
            get { return _isBackSide; }
            set
            {
                if (_isBackSide != value)
                {
                    _isBackSide = value;
                    RaisePropertyChanged(() => IsBackSide);

                }
            }
        }


        private ObservableCollection<BackSideModel> _backSideCollection;
        /// <summary>
        /// Extention property.
        /// </summary>
        public ObservableCollection<BackSideModel> BackSideCollection
        {
            get
            {

                return _backSideCollection;

            }
            set
            {
                if (_backSideCollection != value)
                {
                    _backSideCollection = value;
                    RaisePropertyChanged(() => BackSideCollection);
                }
            }
        }


        #endregion

        #region DataErrorInfo
        [XmlIgnore]
        public string Error
        {
            get { throw new NotImplementedException(); }
        }

        [XmlIgnore]
        private Dictionary<string, string> _errors = new Dictionary<string, string>();

        [XmlIgnore]
        public Dictionary<string, string> Errors
        {
            get
            {
                return _errors;
            }
            set
            {
                if (_errors != value)
                {
                    _errors = value;
                    RaisePropertyChanged(() => Errors);
                }
            }
        }

        
        [XmlIgnore]
        public string this[string columnName]
        {
            get
            {
                string message = String.Empty;
                this.Errors.Remove(columnName);
                switch (columnName)
                {
                    case "LessonName":
                        if (string.IsNullOrWhiteSpace(LessonName))
                            message = "Lesson Name is required!";
                        break;
                    case "Description":
                        if (string.IsNullOrWhiteSpace(Description))
                            message = "Description is required!";
                        break;

                }
                if (!String.IsNullOrEmpty(message))
                {
                    this.Errors.Add(columnName, message);
                }
                return message;
            }
        }
        #endregion

        #endregion
    }
}
