//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using CPC.POSReport.Database;
using Toolkit.Base;

namespace CPC.POSReport.Model
{
    /// <summary>
    /// Model for table base_QuantityAdjustment
    /// </summary>
    [Serializable]
    public partial class base_QuantityAdjustmentModel : ModelBase, IDataErrorInfo
    {
        #region Constructor

        // Default constructor
        public base_QuantityAdjustmentModel()
        {
            this.IsNew = true;
            this.base_QuantityAdjustment = new base_QuantityAdjustment();
        }

        // Default constructor that set entity to field
        public base_QuantityAdjustmentModel(base_QuantityAdjustment base_quantityadjustment, bool isRaiseProperties = false)
        {
            this.base_QuantityAdjustment = base_quantityadjustment;
            if (!isRaiseProperties)
                this.ToModel();
            else
                this.ToModelAndRaise();
            this.IsDirty = false;
        }

        #endregion

        #region Entity Properties

        public base_QuantityAdjustment base_QuantityAdjustment { get; private set; }

        #endregion

        #region Primitive Properties

        protected long _id;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Id</para>
        /// </summary>
        public long Id
        {
            get { return this._id; }
            set
            {
                if (this._id != value)
                {
                    this.IsDirty = true;
                    this._id = value;
                    OnPropertyChanged(() => Id);
                    PropertyChangedCompleted(() => Id);
                }
            }
        }

        protected long _productId;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the ProductId</para>
        /// </summary>
        public long ProductId
        {
            get { return this._productId; }
            set
            {
                if (this._productId != value)
                {
                    this.IsDirty = true;
                    this._productId = value;
                    OnPropertyChanged(() => ProductId);
                    PropertyChangedCompleted(() => ProductId);
                }
            }
        }

        protected string _productResource;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the ProductResource</para>
        /// </summary>
        public string ProductResource
        {
            get { return this._productResource; }
            set
            {
                if (this._productResource != value)
                {
                    this.IsDirty = true;
                    this._productResource = value;
                    OnPropertyChanged(() => ProductResource);
                    PropertyChangedCompleted(() => ProductResource);
                }
            }
        }

        protected decimal _costDifference;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the CostDifference</para>
        /// </summary>
        public decimal CostDifference
        {
            get { return this._costDifference; }
            set
            {
                if (this._costDifference != value)
                {
                    this.IsDirty = true;
                    this._costDifference = value;
                    OnPropertyChanged(() => CostDifference);
                    PropertyChangedCompleted(() => CostDifference);
                }
            }
        }

        protected decimal _oldQty;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the OldQty</para>
        /// </summary>
        public decimal OldQty
        {
            get { return this._oldQty; }
            set
            {
                if (this._oldQty != value)
                {
                    this.IsDirty = true;
                    this._oldQty = value;
                    OnPropertyChanged(() => OldQty);
                    PropertyChangedCompleted(() => OldQty);
                }
            }
        }

        protected decimal _newQty;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the NewQty</para>
        /// </summary>
        public decimal NewQty
        {
            get { return this._newQty; }
            set
            {
                if (this._newQty != value)
                {
                    this.IsDirty = true;
                    this._newQty = value;
                    OnPropertyChanged(() => NewQty);
                    PropertyChangedCompleted(() => NewQty);
                }
            }
        }

        protected decimal _adjustmentQtyDiff;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the AdjustmentQtyDiff</para>
        /// </summary>
        public decimal AdjustmentQtyDiff
        {
            get { return this._adjustmentQtyDiff; }
            set
            {
                if (this._adjustmentQtyDiff != value)
                {
                    this.IsDirty = true;
                    this._adjustmentQtyDiff = value;
                    OnPropertyChanged(() => AdjustmentQtyDiff);
                    PropertyChangedCompleted(() => AdjustmentQtyDiff);
                }
            }
        }

        protected System.DateTime _loggedTime;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the LoggedTime</para>
        /// </summary>
        public System.DateTime LoggedTime
        {
            get { return this._loggedTime; }
            set
            {
                if (this._loggedTime != value)
                {
                    this.IsDirty = true;
                    this._loggedTime = value;
                    OnPropertyChanged(() => LoggedTime);
                    PropertyChangedCompleted(() => LoggedTime);
                }
            }
        }

        protected string _userCreated;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the UserCreated</para>
        /// </summary>
        public string UserCreated
        {
            get { return this._userCreated; }
            set
            {
                if (this._userCreated != value)
                {
                    this.IsDirty = true;
                    this._userCreated = value;
                    OnPropertyChanged(() => UserCreated);
                    PropertyChangedCompleted(() => UserCreated);
                }
            }
        }

        protected Nullable<bool> _isReversed;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the IsReversed</para>
        /// </summary>
        public Nullable<bool> IsReversed
        {
            get { return this._isReversed; }
            set
            {
                if (this._isReversed != value)
                {
                    this.IsDirty = true;
                    this._isReversed = value;
                    OnPropertyChanged(() => IsReversed);
                    PropertyChangedCompleted(() => IsReversed);
                }
            }
        }

        protected Nullable<int> _storeCode;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the StoreCode</para>
        /// </summary>
        public Nullable<int> StoreCode
        {
            get { return this._storeCode; }
            set
            {
                if (this._storeCode != value)
                {
                    this.IsDirty = true;
                    this._storeCode = value;
                    OnPropertyChanged(() => StoreCode);
                    PropertyChangedCompleted(() => StoreCode);
                }
            }
        }

        protected string _resource;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Resource</para>
        /// </summary>
        public string Resource
        {
            get { return this._resource; }
            set
            {
                if (this._resource != value)
                {
                    this.IsDirty = true;
                    this._resource = value;
                    OnPropertyChanged(() => Resource);
                    PropertyChangedCompleted(() => Resource);
                }
            }
        }

        protected short _status;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Status</para>
        /// </summary>
        public short Status
        {
            get { return this._status; }
            set
            {
                if (this._status != value)
                {
                    this.IsDirty = true;
                    this._status = value;
                    OnPropertyChanged(() => Status);
                    PropertyChangedCompleted(() => Status);
                }
            }
        }

        protected short _reason;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Reason</para>
        /// </summary>
        public short Reason
        {
            get { return this._reason; }
            set
            {
                if (this._reason != value)
                {
                    this.IsDirty = true;
                    this._reason = value;
                    OnPropertyChanged(() => Reason);
                    PropertyChangedCompleted(() => Reason);
                }
            }
        }

        protected string _shift;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Shift</para>
        /// </summary>
        public string Shift
        {
            get { return this._shift; }
            set
            {
                if (this._shift != value)
                {
                    this.IsDirty = true;
                    this._shift = value;
                    OnPropertyChanged(() => Shift);
                    PropertyChangedCompleted(() => Shift);
                }
            }
        }

        #endregion

        #region Public Methods

        /// <summary>
        /// <para>Public Method</para>
        /// Method for set IsNew & IsDirty = false;
        /// </summary>
        public void EndUpdate()
        {
            this.IsNew = false;
            this.IsDirty = false;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set PropertyModel to Entity</para>
        /// </summary>
        public void ToEntity()
        {
            if (IsNew)
                this.base_QuantityAdjustment.Id = this.Id;
            this.base_QuantityAdjustment.ProductId = this.ProductId;
            this.base_QuantityAdjustment.ProductResource = this.ProductResource;
            this.base_QuantityAdjustment.CostDifference = this.CostDifference;
            this.base_QuantityAdjustment.OldQty = this.OldQty;
            this.base_QuantityAdjustment.NewQty = this.NewQty;
            this.base_QuantityAdjustment.AdjustmentQtyDiff = this.AdjustmentQtyDiff;
            this.base_QuantityAdjustment.LoggedTime = this.LoggedTime;
            this.base_QuantityAdjustment.UserCreated = this.UserCreated;
            this.base_QuantityAdjustment.IsReversed = this.IsReversed;
            this.base_QuantityAdjustment.StoreCode = this.StoreCode;
            this.base_QuantityAdjustment.Resource = this.Resource;
            this.base_QuantityAdjustment.Status = this.Status;
            this.base_QuantityAdjustment.Reason = this.Reason;
            this.base_QuantityAdjustment.Shift = this.Shift;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set Entity to PropertyModel</para>
        /// </summary
        public void ToModel()
        {
            this._id = this.base_QuantityAdjustment.Id;
            this._productId = this.base_QuantityAdjustment.ProductId;
            this._productResource = this.base_QuantityAdjustment.ProductResource;
            this._costDifference = this.base_QuantityAdjustment.CostDifference;
            this._oldQty = this.base_QuantityAdjustment.OldQty;
            this._newQty = this.base_QuantityAdjustment.NewQty;
            this._adjustmentQtyDiff = this.base_QuantityAdjustment.AdjustmentQtyDiff;
            this._loggedTime = this.base_QuantityAdjustment.LoggedTime;
            this._userCreated = this.base_QuantityAdjustment.UserCreated;
            this._isReversed = this.base_QuantityAdjustment.IsReversed;
            this._storeCode = this.base_QuantityAdjustment.StoreCode;
            this._resource = this.base_QuantityAdjustment.Resource;
            this._status = this.base_QuantityAdjustment.Status;
            this._reason = this.base_QuantityAdjustment.Reason;
            this._shift = this.base_QuantityAdjustment.Shift;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set Entity to PropertyModel</para>
        /// </summary
        public void ToModelAndRaise()
        {
            this.Id = this.base_QuantityAdjustment.Id;
            this.ProductId = this.base_QuantityAdjustment.ProductId;
            this.ProductResource = this.base_QuantityAdjustment.ProductResource;
            this.CostDifference = this.base_QuantityAdjustment.CostDifference;
            this.OldQty = this.base_QuantityAdjustment.OldQty;
            this.NewQty = this.base_QuantityAdjustment.NewQty;
            this.AdjustmentQtyDiff = this.base_QuantityAdjustment.AdjustmentQtyDiff;
            this.LoggedTime = this.base_QuantityAdjustment.LoggedTime;
            this.UserCreated = this.base_QuantityAdjustment.UserCreated;
            this.IsReversed = this.base_QuantityAdjustment.IsReversed;
            this.StoreCode = this.base_QuantityAdjustment.StoreCode;
            this.Resource = this.base_QuantityAdjustment.Resource;
            this.Status = this.base_QuantityAdjustment.Status;
            this.Reason = this.base_QuantityAdjustment.Reason;
            this.Shift = this.base_QuantityAdjustment.Shift;
        }

        #endregion

        #region Custom Code


        #endregion

        #region IDataErrorInfo Members

        public string Error
        {
            get { throw new NotImplementedException(); }
        }

        public string this[string columnName]
        {
            get
            {
                string message = string.Empty;

                switch (columnName)
                {
                    case "Id":
                        break;
                    case "ProductId":
                        break;
                    case "ProductResource":
                        break;
                    case "CostDifference":
                        break;
                    case "OldQty":
                        break;
                    case "NewQty":
                        break;
                    case "AdjustmentQtyDiff":
                        break;
                    case "LoggedTime":
                        break;
                    case "UserCreated":
                        break;
                    case "IsReversed":
                        break;
                    case "StoreCode":
                        break;
                    case "Resource":
                        break;
                    case "Status":
                        break;
                    case "Reason":
                        break;
                }

                if (!string.IsNullOrWhiteSpace(message))
                    return message;
                return null;
            }
        }

        #endregion
    }
}
