//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using CPC.POSReport.Database;
using Toolkit.Base;

namespace CPC.POSReport.Model
{
    /// <summary>
    /// Model for table pga_jobstep
    /// </summary>
    [Serializable]
    public partial class pga_jobstepModel : ModelBase, IDataErrorInfo
    {
        #region Constructor

        // Default constructor
        public pga_jobstepModel()
        {
            this.IsNew = true;
            this.pga_jobstep = new pga_jobstep();
        }

        // Default constructor that set entity to field
        public pga_jobstepModel(pga_jobstep pga_jobstep, bool isRaiseProperties = false)
        {
            this.pga_jobstep = pga_jobstep;
            if (!isRaiseProperties)
                this.ToModel();
            else
                this.ToModelAndRaise();
            this.IsDirty = false;
        }

        #endregion

        #region Entity Properties

        public pga_jobstep pga_jobstep { get; private set; }

        #endregion

        #region Primitive Properties

        protected int _jstid;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the jstid</para>
        /// </summary>
        public int jstid
        {
            get { return this._jstid; }
            set
            {
                if (this._jstid != value)
                {
                    this.IsDirty = true;
                    this._jstid = value;
                    OnPropertyChanged(() => jstid);
                    PropertyChangedCompleted(() => jstid);
                }
            }
        }

        protected int _jstjobid;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the jstjobid</para>
        /// </summary>
        public int jstjobid
        {
            get { return this._jstjobid; }
            set
            {
                if (this._jstjobid != value)
                {
                    this.IsDirty = true;
                    this._jstjobid = value;
                    OnPropertyChanged(() => jstjobid);
                    PropertyChangedCompleted(() => jstjobid);
                }
            }
        }

        protected string _jstname;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the jstname</para>
        /// </summary>
        public string jstname
        {
            get { return this._jstname; }
            set
            {
                if (this._jstname != value)
                {
                    this.IsDirty = true;
                    this._jstname = value;
                    OnPropertyChanged(() => jstname);
                    PropertyChangedCompleted(() => jstname);
                }
            }
        }

        protected string _jstdesc;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the jstdesc</para>
        /// </summary>
        public string jstdesc
        {
            get { return this._jstdesc; }
            set
            {
                if (this._jstdesc != value)
                {
                    this.IsDirty = true;
                    this._jstdesc = value;
                    OnPropertyChanged(() => jstdesc);
                    PropertyChangedCompleted(() => jstdesc);
                }
            }
        }

        protected bool _jstenabled;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the jstenabled</para>
        /// </summary>
        public bool jstenabled
        {
            get { return this._jstenabled; }
            set
            {
                if (this._jstenabled != value)
                {
                    this.IsDirty = true;
                    this._jstenabled = value;
                    OnPropertyChanged(() => jstenabled);
                    PropertyChangedCompleted(() => jstenabled);
                }
            }
        }

        protected string _jstkind;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the jstkind</para>
        /// </summary>
        public string jstkind
        {
            get { return this._jstkind; }
            set
            {
                if (this._jstkind != value)
                {
                    this.IsDirty = true;
                    this._jstkind = value;
                    OnPropertyChanged(() => jstkind);
                    PropertyChangedCompleted(() => jstkind);
                }
            }
        }

        protected string _jstcode;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the jstcode</para>
        /// </summary>
        public string jstcode
        {
            get { return this._jstcode; }
            set
            {
                if (this._jstcode != value)
                {
                    this.IsDirty = true;
                    this._jstcode = value;
                    OnPropertyChanged(() => jstcode);
                    PropertyChangedCompleted(() => jstcode);
                }
            }
        }

        protected string _jstconnstr;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the jstconnstr</para>
        /// </summary>
        public string jstconnstr
        {
            get { return this._jstconnstr; }
            set
            {
                if (this._jstconnstr != value)
                {
                    this.IsDirty = true;
                    this._jstconnstr = value;
                    OnPropertyChanged(() => jstconnstr);
                    PropertyChangedCompleted(() => jstconnstr);
                }
            }
        }

        protected string _jstonerror;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the jstonerror</para>
        /// </summary>
        public string jstonerror
        {
            get { return this._jstonerror; }
            set
            {
                if (this._jstonerror != value)
                {
                    this.IsDirty = true;
                    this._jstonerror = value;
                    OnPropertyChanged(() => jstonerror);
                    PropertyChangedCompleted(() => jstonerror);
                }
            }
        }

        protected Nullable<System.DateTimeOffset> _jscnextrun;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the jscnextrun</para>
        /// </summary>
        public Nullable<System.DateTimeOffset> jscnextrun
        {
            get { return this._jscnextrun; }
            set
            {
                if (this._jscnextrun != value)
                {
                    this.IsDirty = true;
                    this._jscnextrun = value;
                    OnPropertyChanged(() => jscnextrun);
                    PropertyChangedCompleted(() => jscnextrun);
                }
            }
        }

        #endregion

        #region Public Methods

        /// <summary>
        /// <para>Public Method</para>
        /// Method for set IsNew & IsDirty = false;
        /// </summary>
        public void EndUpdate()
        {
            this.IsNew = false;
            this.IsDirty = false;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set PropertyModel to Entity</para>
        /// </summary>
        public void ToEntity()
        {
            if (IsNew)
                this.pga_jobstep.jstid = this.jstid;
            this.pga_jobstep.jstjobid = this.jstjobid;
            this.pga_jobstep.jstname = this.jstname;
            this.pga_jobstep.jstdesc = this.jstdesc;
            this.pga_jobstep.jstenabled = this.jstenabled;
            this.pga_jobstep.jstkind = this.jstkind;
            this.pga_jobstep.jstcode = this.jstcode;
            this.pga_jobstep.jstconnstr = this.jstconnstr;
            this.pga_jobstep.jstonerror = this.jstonerror;
            this.pga_jobstep.jscnextrun = this.jscnextrun;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set Entity to PropertyModel</para>
        /// </summary
        public void ToModel()
        {
            this._jstid = this.pga_jobstep.jstid;
            this._jstjobid = this.pga_jobstep.jstjobid;
            this._jstname = this.pga_jobstep.jstname;
            this._jstdesc = this.pga_jobstep.jstdesc;
            this._jstenabled = this.pga_jobstep.jstenabled;
            this._jstkind = this.pga_jobstep.jstkind;
            this._jstcode = this.pga_jobstep.jstcode;
            this._jstconnstr = this.pga_jobstep.jstconnstr;
            this._jstonerror = this.pga_jobstep.jstonerror;
            this._jscnextrun = this.pga_jobstep.jscnextrun;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set Entity to PropertyModel</para>
        /// </summary
        public void ToModelAndRaise()
        {
            this.jstid = this.pga_jobstep.jstid;
            this.jstjobid = this.pga_jobstep.jstjobid;
            this.jstname = this.pga_jobstep.jstname;
            this.jstdesc = this.pga_jobstep.jstdesc;
            this.jstenabled = this.pga_jobstep.jstenabled;
            this.jstkind = this.pga_jobstep.jstkind;
            this.jstcode = this.pga_jobstep.jstcode;
            this.jstconnstr = this.pga_jobstep.jstconnstr;
            this.jstonerror = this.pga_jobstep.jstonerror;
            this.jscnextrun = this.pga_jobstep.jscnextrun;
        }

        #endregion

        #region Custom Code


        #endregion

        #region IDataErrorInfo Members

        public string Error
        {
            get { throw new NotImplementedException(); }
        }

        public string this[string columnName]
        {
            get
            {
                string message = string.Empty;

                switch (columnName)
                {
                    case "jstid":
                        break;
                    case "jstjobid":
                        break;
                    case "jstname":
                        break;
                    case "jstdesc":
                        break;
                    case "jstenabled":
                        break;
                    case "jstkind":
                        break;
                    case "jstcode":
                        break;
                    case "jstconnstr":
                        break;
                    case "jstonerror":
                        break;
                    case "jscnextrun":
                        break;
                }

                if (!string.IsNullOrWhiteSpace(message))
                    return message;
                return null;
            }
        }

        #endregion
    }
}
