//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using CPC.POSReport.Database;
using Toolkit.Base;

namespace CPC.POSReport.Model
{
    /// <summary>
    /// Model for table rpt_Report
    /// </summary>
    [Serializable]
    public partial class rpt_ReportModel : ModelBase, IDataErrorInfo
    {
        #region Constructor

        // Default constructor
        public rpt_ReportModel()
        {
            this.IsNew = true;
            this.rpt_Report = new rpt_Report();
        }

        // Default constructor that set entity to field
        public rpt_ReportModel(rpt_Report rpt_report, bool isRaiseProperties = false)
        {
            this.rpt_Report = rpt_report;
            if (!isRaiseProperties)
                this.ToModel();
            else
                this.ToModelAndRaise();
            this.IsDirty = false;
        }

        #endregion

        #region Entity Properties

        public rpt_Report rpt_Report { get; private set; }

        #endregion

        #region Primitive Properties

        protected int _id;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Id</para>
        /// </summary>
        public int Id
        {
            get { return this._id; }
            set
            {
                if (this._id != value)
                {
                    this.IsDirty = true;
                    this._id = value;
                    OnPropertyChanged(() => Id);
                    PropertyChangedCompleted(() => Id);
                }
            }
        }

        protected int _groupId;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the GroupId</para>
        /// </summary>
        public int GroupId
        {
            get { return this._groupId; }
            set
            {
                if (this._groupId != value)
                {
                    this.IsDirty = true;
                    this._groupId = value;
                    OnPropertyChanged(() => GroupId);
                    PropertyChangedCompleted(() => GroupId);
                }
            }
        }

        protected int _parentId;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the ParentId</para>
        /// </summary>
        public int ParentId
        {
            get { return this._parentId; }
            set
            {
                if (this._parentId != value)
                {
                    this.IsDirty = true;
                    this._parentId = value;
                    OnPropertyChanged(() => ParentId);
                    PropertyChangedCompleted(() => ParentId);
                }
            }
        }

        protected string _code;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Code</para>
        /// </summary>
        public string Code
        {
            get { return this._code; }
            set
            {
                if (this._code != value)
                {
                    this.IsDirty = true;
                    this._code = value;
                    OnPropertyChanged(() => Code);
                    PropertyChangedCompleted(() => Code);
                }
            }
        }

        protected string _name;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Name</para>
        /// </summary>
        public string Name
        {
            get { return this._name; }
            set
            {
                if (this._name != value)
                {
                    this.IsDirty = true;
                    this._name = value;
                    OnPropertyChanged(() => Name);
                    PropertyChangedCompleted(() => Name);
                }
            }
        }

        protected string _formatFile;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the FormatFile</para>
        /// </summary>
        public string FormatFile
        {
            get { return this._formatFile; }
            set
            {
                if (this._formatFile != value)
                {
                    this.IsDirty = true;
                    this._formatFile = value;
                    OnPropertyChanged(() => FormatFile);
                    PropertyChangedCompleted(() => FormatFile);
                }
            }
        }

        protected bool _isShow;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the IsShow</para>
        /// </summary>
        public bool IsShow
        {
            get { return this._isShow; }
            set
            {
                if (this._isShow != value)
                {
                    this.IsDirty = true;
                    this._isShow = value;
                    OnPropertyChanged(() => IsShow);
                    PropertyChangedCompleted(() => IsShow);
                }
            }
        }

        protected string _preProcessName;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the PreProcessName</para>
        /// </summary>
        public string PreProcessName
        {
            get { return this._preProcessName; }
            set
            {
                if (this._preProcessName != value)
                {
                    this.IsDirty = true;
                    this._preProcessName = value;
                    OnPropertyChanged(() => PreProcessName);
                    PropertyChangedCompleted(() => PreProcessName);
                }
            }
        }

        protected byte[] _samplePicture;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the SamplePicture</para>
        /// </summary>
        public byte[] SamplePicture
        {
            get { return this._samplePicture; }
            set
            {
                if (this._samplePicture != value)
                {
                    this.IsDirty = true;
                    this._samplePicture = value;
                    OnPropertyChanged(() => SamplePicture);
                    PropertyChangedCompleted(() => SamplePicture);
                }
            }
        }

        protected int _printTimes;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the PrintTimes</para>
        /// </summary>
        public int PrintTimes
        {
            get { return this._printTimes; }
            set
            {
                if (this._printTimes != value)
                {
                    this.IsDirty = true;
                    this._printTimes = value;
                    OnPropertyChanged(() => PrintTimes);
                    PropertyChangedCompleted(() => PrintTimes);
                }
            }
        }

        protected Nullable<System.DateTime> _lastPrintDate;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the LastPrintDate</para>
        /// </summary>
        public Nullable<System.DateTime> LastPrintDate
        {
            get { return this._lastPrintDate; }
            set
            {
                if (this._lastPrintDate != value)
                {
                    this.IsDirty = true;
                    this._lastPrintDate = value;
                    OnPropertyChanged(() => LastPrintDate);
                    PropertyChangedCompleted(() => LastPrintDate);
                }
            }
        }

        protected string _lastPrintUser;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the LastPrintUser</para>
        /// </summary>
        public string LastPrintUser
        {
            get { return this._lastPrintUser; }
            set
            {
                if (this._lastPrintUser != value)
                {
                    this.IsDirty = true;
                    this._lastPrintUser = value;
                    OnPropertyChanged(() => LastPrintUser);
                    PropertyChangedCompleted(() => LastPrintUser);
                }
            }
        }

        protected string _excelFile;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the ExcelFile</para>
        /// </summary>
        public string ExcelFile
        {
            get { return this._excelFile; }
            set
            {
                if (this._excelFile != value)
                {
                    this.IsDirty = true;
                    this._excelFile = value;
                    OnPropertyChanged(() => ExcelFile);
                    PropertyChangedCompleted(() => ExcelFile);
                }
            }
        }

        protected string _printerName;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the PrinterName</para>
        /// </summary>
        public string PrinterName
        {
            get { return this._printerName; }
            set
            {
                if (this._printerName != value)
                {
                    this.IsDirty = true;
                    this._printerName = value;
                    OnPropertyChanged(() => PrinterName);
                    PropertyChangedCompleted(() => PrinterName);
                }
            }
        }

        protected short _printCopy;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the PrintCopy</para>
        /// </summary>
        public short PrintCopy
        {
            get { return this._printCopy; }
            set
            {
                if (this._printCopy != value)
                {
                    this.IsDirty = true;
                    this._printCopy = value;
                    OnPropertyChanged(() => PrintCopy);
                    PropertyChangedCompleted(() => PrintCopy);
                }
            }
        }

        protected string _remark;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Remark</para>
        /// </summary>
        public string Remark
        {
            get { return this._remark; }
            set
            {
                if (this._remark != value)
                {
                    this.IsDirty = true;
                    this._remark = value;
                    OnPropertyChanged(() => Remark);
                    PropertyChangedCompleted(() => Remark);
                }
            }
        }

        protected Nullable<System.DateTime> _dateCreated;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the DateCreated</para>
        /// </summary>
        public Nullable<System.DateTime> DateCreated
        {
            get { return this._dateCreated; }
            set
            {
                if (this._dateCreated != value)
                {
                    this.IsDirty = true;
                    this._dateCreated = value;
                    OnPropertyChanged(() => DateCreated);
                    PropertyChangedCompleted(() => DateCreated);
                }
            }
        }

        protected string _userCreated;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the UserCreated</para>
        /// </summary>
        public string UserCreated
        {
            get { return this._userCreated; }
            set
            {
                if (this._userCreated != value)
                {
                    this.IsDirty = true;
                    this._userCreated = value;
                    OnPropertyChanged(() => UserCreated);
                    PropertyChangedCompleted(() => UserCreated);
                }
            }
        }

        protected Nullable<System.DateTime> _dateUpdated;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the DateUpdated</para>
        /// </summary>
        public Nullable<System.DateTime> DateUpdated
        {
            get { return this._dateUpdated; }
            set
            {
                if (this._dateUpdated != value)
                {
                    this.IsDirty = true;
                    this._dateUpdated = value;
                    OnPropertyChanged(() => DateUpdated);
                    PropertyChangedCompleted(() => DateUpdated);
                }
            }
        }

        protected string _userUpdated;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the UserUpdated</para>
        /// </summary>
        public string UserUpdated
        {
            get { return this._userUpdated; }
            set
            {
                if (this._userUpdated != value)
                {
                    this.IsDirty = true;
                    this._userUpdated = value;
                    OnPropertyChanged(() => UserUpdated);
                    PropertyChangedCompleted(() => UserUpdated);
                }
            }
        }

        protected short _paperSize;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the PaperSize</para>
        /// </summary>
        public short PaperSize
        {
            get { return this._paperSize; }
            set
            {
                if (this._paperSize != value)
                {
                    this.IsDirty = true;
                    this._paperSize = value;
                    OnPropertyChanged(() => PaperSize);
                    PropertyChangedCompleted(() => PaperSize);
                }
            }
        }

        protected int _screenTimes;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the ScreenTimes</para>
        /// </summary>
        public int ScreenTimes
        {
            get { return this._screenTimes; }
            set
            {
                if (this._screenTimes != value)
                {
                    this.IsDirty = true;
                    this._screenTimes = value;
                    OnPropertyChanged(() => ScreenTimes);
                    PropertyChangedCompleted(() => ScreenTimes);
                }
            }
        }

        protected string _prepProcessDescription;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the PrepProcessDescription</para>
        /// </summary>
        public string PrepProcessDescription
        {
            get { return this._prepProcessDescription; }
            set
            {
                if (this._prepProcessDescription != value)
                {
                    this.IsDirty = true;
                    this._prepProcessDescription = value;
                    OnPropertyChanged(() => PrepProcessDescription);
                    PropertyChangedCompleted(() => PrepProcessDescription);
                }
            }
        }

        protected string _cCReport;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the CCReport</para>
        /// </summary>
        public string CCReport
        {
            get { return this._cCReport; }
            set
            {
                if (this._cCReport != value)
                {
                    this.IsDirty = true;
                    this._cCReport = value;
                    OnPropertyChanged(() => CCReport);
                    PropertyChangedCompleted(() => CCReport);
                }
            }
        }

        #endregion

        #region Public Methods

        /// <summary>
        /// <para>Public Method</para>
        /// Method for set IsNew & IsDirty = false;
        /// </summary>
        public void EndUpdate()
        {
            this.IsNew = false;
            this.IsDirty = false;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set PropertyModel to Entity</para>
        /// </summary>
        public void ToEntity()
        {
            if (IsNew)
                this.rpt_Report.Id = this.Id;
            this.rpt_Report.GroupId = this.GroupId;
            this.rpt_Report.ParentId = this.ParentId;
            this.rpt_Report.Code = this.Code;
            this.rpt_Report.Name = this.Name;
            this.rpt_Report.FormatFile = this.FormatFile;
            this.rpt_Report.IsShow = this.IsShow;
            this.rpt_Report.PreProcessName = this.PreProcessName;
            this.rpt_Report.SamplePicture = this.SamplePicture;
            this.rpt_Report.PrintTimes = this.PrintTimes;
            this.rpt_Report.LastPrintDate = this.LastPrintDate;
            this.rpt_Report.LastPrintUser = this.LastPrintUser;
            this.rpt_Report.ExcelFile = this.ExcelFile;
            this.rpt_Report.PrinterName = this.PrinterName;
            this.rpt_Report.PrintCopy = this.PrintCopy;
            this.rpt_Report.Remark = this.Remark;
            this.rpt_Report.DateCreated = this.DateCreated;
            this.rpt_Report.UserCreated = this.UserCreated;
            this.rpt_Report.DateUpdated = this.DateUpdated;
            this.rpt_Report.UserUpdated = this.UserUpdated;
            this.rpt_Report.PaperSize = this.PaperSize;
            this.rpt_Report.ScreenTimes = this.ScreenTimes;
            this.rpt_Report.PrepProcessDescription = this.PrepProcessDescription;
            this.rpt_Report.CCReport = this.CCReport;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set Entity to PropertyModel</para>
        /// </summary
        public void ToModel()
        {
            this._id = this.rpt_Report.Id;
            this._groupId = this.rpt_Report.GroupId;
            this._parentId = this.rpt_Report.ParentId;
            this._code = this.rpt_Report.Code;
            this._name = this.rpt_Report.Name;
            this._formatFile = this.rpt_Report.FormatFile;
            this._isShow = this.rpt_Report.IsShow;
            this._preProcessName = this.rpt_Report.PreProcessName;
            this._samplePicture = this.rpt_Report.SamplePicture;
            this._printTimes = this.rpt_Report.PrintTimes;
            this._lastPrintDate = this.rpt_Report.LastPrintDate;
            this._lastPrintUser = this.rpt_Report.LastPrintUser;
            this._excelFile = this.rpt_Report.ExcelFile;
            this._printerName = this.rpt_Report.PrinterName;
            this._printCopy = this.rpt_Report.PrintCopy;
            this._remark = this.rpt_Report.Remark;
            this._dateCreated = this.rpt_Report.DateCreated;
            this._userCreated = this.rpt_Report.UserCreated;
            this._dateUpdated = this.rpt_Report.DateUpdated;
            this._userUpdated = this.rpt_Report.UserUpdated;
            this._paperSize = this.rpt_Report.PaperSize;
            this._screenTimes = this.rpt_Report.ScreenTimes;
            this._prepProcessDescription = this.rpt_Report.PrepProcessDescription;
            this._cCReport = this.rpt_Report.CCReport;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set Entity to PropertyModel</para>
        /// </summary
        public void ToModelAndRaise()
        {
            this.Id = this.rpt_Report.Id;
            this.GroupId = this.rpt_Report.GroupId;
            this.ParentId = this.rpt_Report.ParentId;
            this.Code = this.rpt_Report.Code;
            this.Name = this.rpt_Report.Name;
            this.FormatFile = this.rpt_Report.FormatFile;
            this.IsShow = this.rpt_Report.IsShow;
            this.PreProcessName = this.rpt_Report.PreProcessName;
            this.SamplePicture = this.rpt_Report.SamplePicture;
            this.PrintTimes = this.rpt_Report.PrintTimes;
            this.LastPrintDate = this.rpt_Report.LastPrintDate;
            this.LastPrintUser = this.rpt_Report.LastPrintUser;
            this.ExcelFile = this.rpt_Report.ExcelFile;
            this.PrinterName = this.rpt_Report.PrinterName;
            this.PrintCopy = this.rpt_Report.PrintCopy;
            this.Remark = this.rpt_Report.Remark;
            this.DateCreated = this.rpt_Report.DateCreated;
            this.UserCreated = this.rpt_Report.UserCreated;
            this.DateUpdated = this.rpt_Report.DateUpdated;
            this.UserUpdated = this.rpt_Report.UserUpdated;
            this.PaperSize = this.rpt_Report.PaperSize;
            this.ScreenTimes = this.rpt_Report.ScreenTimes;
            this.PrepProcessDescription = this.rpt_Report.PrepProcessDescription;
            this.CCReport = this.rpt_Report.CCReport;
        }

        #endregion

        #region Custom Code

        // Default constructor that set entity to field
        public rpt_ReportModel(rpt_Report rpt_report)
        {
            this.rpt_Report = rpt_report;
            this.ToModel();
            this.IsDirty = false;

            this.GroupName = this.rpt_Report.rpt_Group.Name;
            Children = new ObservableCollection<rpt_ReportModel>();
        }

        public rpt_ReportModel(rpt_Report rpt_report, rpt_ReportModel parent)
        {
            this.rpt_Report = rpt_report;
            this.ToModel();
            this.IsDirty = false;
            
            this.GroupName = this.rpt_Report.rpt_Group.Name;
            Parent = parent;
            Children = new ObservableCollection<rpt_ReportModel>();
        }

        #region Parent

        private rpt_ReportModel _parent;
        public rpt_ReportModel Parent
        {
            get { return _parent; }
            set
            {
                _parent = value;
            }
        }

        #endregion

        #region -Is Show Open Foler Property-
        /// <summary>
        /// Set or get Is Show open foder Property
        /// </summary>
        protected string _isShowOpenFolder;
        public string IsShowOpenFolder
        {
            get { return _isShowOpenFolder; }
            set
            {
                if (_isShowOpenFolder != value)
                {
                    _isShowOpenFolder = value;
                    OnPropertyChanged(() => IsShowOpenFolder);
                }
            }
        }
        #endregion

        #region -Is Show Close Foler Property-
        /// <summary>
        /// Set or get Is close open foder Property
        /// </summary>
        protected string _isShowCloseFolder;
        public string IsShowCloseFolder
        {
            get { return _isShowCloseFolder; }
            set
            {
                if (_isShowCloseFolder != value)
                {
                    _isShowCloseFolder = value;
                    OnPropertyChanged(() => IsShowCloseFolder);
                }
            }
        }
        #endregion

        #region -Is Show document Property-
        /// <summary>
        /// Set or get Is Show document Property
        /// </summary>
        protected string _isShowDocumentr;
        public string IsShowDocument
        {
            get { return _isShowDocumentr; }
            set
            {
                if (_isShowDocumentr != value)
                {
                    _isShowDocumentr = value;
                    OnPropertyChanged(() => IsShowDocument);
                }
            }
        }
        #endregion

        #region -Is Show Ok Property-
        /// <summary>
        /// Set or get Is Show OK Property
        /// </summary>
        protected string _isShowOK = "Collapsed";
        public string IsShowOK
        {
            get { return _isShowOK; }
            set
            {
                if (_isShowOK != value)
                {
                    _isShowOK = value;
                    OnPropertyChanged(() => IsShowOK);
                }
            }
        }
        #endregion

        protected bool _isView;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the IsView</para>
        /// </summary>
        public bool IsView
        {
            get { return this._isView; }
            set
            {
                if (this._isView != value)
                {
                    this.IsDirty = true;
                    this._isView = value;
                    OnPropertyChanged(() => IsView);
                    PropertyChangedCompleted(() => IsView);
                }
            }
        }

        protected bool _isPrint;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the IsPrint</para>
        /// </summary>
        public bool IsPrint
        {
            get { return this._isPrint; }
            set
            {
                if (this._isPrint != value)
                {
                    this.IsDirty = true;
                    this._isPrint = value;
                    OnPropertyChanged(() => IsPrint);
                    PropertyChangedCompleted(() => IsPrint);
                }
            }
        }

        protected string _groupName;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Name</para>
        /// </summary>
        public string GroupName
        {
            get { return this._groupName; }
            set
            {
                if (this._groupName != value)
                {
                    this.IsDirty = true;
                    this._groupName = value;
                    OnPropertyChanged(() => GroupName);
                    PropertyChangedCompleted(() => GroupName);
                }
            }
        }

        // Default constructor that set entity to field
        public rpt_ReportModel(rpt_Report rpt_report, int isExtend)
        {
            this.rpt_Report = rpt_report;
            this.ToModel();
            this.IsDirty = false;
            this.GroupName = this.rpt_Report.rpt_Group.Name;
            Children = new ObservableCollection<rpt_ReportModel>();
        }

        private ObservableCollection<rpt_ReportModel> _children;
        public ObservableCollection<rpt_ReportModel> Children
        {
            get { return _children; }
            set
            {
                if (_children != value)
                {
                    _children = value;
                }
            }
        }

        protected string _paperName;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Name</para>
        /// </summary>
        public string PaperName
        {
            get { return this._paperName; }
            set
            {
                if (this._paperName != value)
                {
                    this.IsDirty = true;
                    this._paperName = value;
                    OnPropertyChanged(() => PaperName);
                    PropertyChangedCompleted(() => PaperName);
                }
            }
        }

        protected bool _isDefaultPrinter = true;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the IsDefaultPrinter</para>
        /// </summary>
        public bool IsDefaultPrinter
        {
            get { return this._isDefaultPrinter; }
            set
            {
                if (this._isDefaultPrinter != value)
                {
                    this.IsDirty = true;
                    this._isDefaultPrinter = value;
                    OnPropertyChanged(() => IsDefaultPrinter);
                    PropertyChangedCompleted(() => IsDefaultPrinter);
                }
            }
        }

        protected override void PropertyChangedCompleted(string propertyName)
        {
            base.PropertyChangedCompleted(propertyName);
            if (propertyName == "IsDefaultPrinter")
            {
                this.IsDirty = true;
            }
        }

        public string Error
        {
            get { return null; }
        }

        /// <summary>
        /// Get or set Errors string.
        /// </summary>
        protected Dictionary<string, string> _errors = new Dictionary<string, string>();
        public Dictionary<string, string> Errors
        {
            get { return _errors; }
        }

        #endregion

        #region IDataErrorInfo Members
        public string this[string columnName]
        {
            get
            {
                string message = string.Empty;
                this.Errors.Remove(columnName);
                switch (columnName)
                {
                    case "Id":
                        break;
                    case "GroupId":
                        break;
                    case "ParentId":
                        break;
                    case "Code":
                        if (string.IsNullOrEmpty(Code))
                        {
                            message = "Code is required";
                        }
                        break;
                    case "Name":
                        if (string.IsNullOrEmpty(Name))
                        {
                            message = "Name is required";
                        }
                        break;
                    case "FormatFile":
                        break;
                    case "IsShow":
                        break;
                    case "PreProcessName":
                        break;
                    case "SamplePicture":
                        break;
                    case "PrintTimes":
                        break;
                    case "LastPrintDate":
                        break;
                    case "LastPrintUser":
                        break;
                    case "ExcelFile":
                        break;
                    case "PrinterName":
                        break;
                    case "PrintCopy":
                        break;
                    case "Remark":
                        break;
                    case "DateCreated":
                        break;
                    case "UserCreated":
                        break;
                    case "DateUpdated":
                        break;
                    case "UserUpdated":
                        break;
                    case "PaperSize":
                        break;
                    case "ScreenTimes":
                        break;
                    case "PrepProcessDescription":
                        break;
                }

                if (!string.IsNullOrWhiteSpace(message))
                {
                    this.Errors.Add(columnName, message);
                }
                return message;
            }
        }

        #endregion
    }
}
