//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data.Objects;
using System.Linq;
using System.Linq.Expressions;
using CPC.POS.Database;

namespace CPC.POS.Repository
{
    /// <summary>
    /// Repository for table base_Department 
    /// </summary>
    public partial class base_DepartmentRepository
    {
        #region Auto Generate Code

        #region Constructors

        // Default constructor
        public base_DepartmentRepository()
        {
        }

        #endregion

        #region Basic C.R.U.D. Operations

        /// <summary>
        /// Add new base_Department.
        /// </summary>
        /// <param name="base_Department">base_Department to add.</param>
        /// <returns>base_Department have been added.</returns>
        public base_Department Add(base_Department base_Department)
        {
            UnitOfWork.Add<base_Department>(base_Department);
            return base_Department;
        }

        /// <summary>
        /// Adds a sequence of new base_Department.
        /// </summary>
        /// <param name="base_Department">Sequence of new base_Department to add.</param>
        /// <returns>Sequence of new base_Department have been added.</returns>
        public IEnumerable<base_Department> Add(IEnumerable<base_Department> base_Department)
        {
            UnitOfWork.Add<base_Department>(base_Department);
            return base_Department;
        }

        /// <summary>
        /// Delete a existed base_Department.
        /// </summary>
        /// <param name="base_Department">base_Department to delete.</param>
        public void Delete(base_Department base_Department)
        {
            Refresh(base_Department);
            if (base_Department.EntityState != System.Data.EntityState.Detached)
                UnitOfWork.Delete<base_Department>(base_Department);
        }

        /// <summary>
        /// Delete a sequence of existed base_Department.
        /// </summary>
        /// <param name="base_Department">Sequence of existed base_Department to delete.</param>
        public void Delete(IEnumerable<base_Department> base_Department)
        {
            int total = base_Department.Count();
            for (int i = total - 1; i >= 0; i--)
                Delete(base_Department.ElementAt(i));
        }

        /// <summary>
        /// Returns the first base_Department of a sequence that satisfies a specified condition or 
        /// a default value if no such base_Department is found.
        /// </summary>
        /// <param name="expression">A function to test each base_Department for a condition.</param>
        /// <returns>    
        /// Null if source is empty or if no base_Department passes the test specified by expression; 
        /// otherwise, the first base_Department in source that passes the test specified by expression.
        /// </returns>
        public base_Department Get(Expression<Func<base_Department, bool>> expression)
        {
            return UnitOfWork.Get<base_Department>(expression);
        }

        /// <summary>
        /// Get all base_Department.
        /// </summary>
        /// <returns>The new IList&lt;base_Department&gt; instance.</returns>
        public IList<base_Department> GetAll()
        {
            return UnitOfWork.GetAll<base_Department>();
        }

        /// <summary>
        /// Get all base_Department that satisfies a specified condition.
        /// </summary>
        /// <param name="expression">A function to test each base_Department for a condition.</param>
        /// <returns>The new IList&lt;base_Department&gt; instance.</returns>
        public IList<base_Department> GetAll(Expression<Func<base_Department, bool>> expression)
        {
            return UnitOfWork.GetAll<base_Department>(expression);
        }

        /// <summary>
        /// Get all base_Department.
        /// </summary>
        /// <returns>The new IEnumerable&lt;base_Department&gt; instance.</returns>
        public IEnumerable<base_Department> GetIEnumerable()
        {
            return UnitOfWork.GetIEnumerable<base_Department>();
        }

        /// <summary>
        /// Get all base_Department that satisfies a specified condition.
        /// </summary>
        /// <param name="expression">A function to test each base_Department for a condition.</param>
        /// <returns>The new IEnumerable&lt;base_Department&gt; instance.</returns>
        public IEnumerable<base_Department> GetIEnumerable(Expression<Func<base_Department, bool>> expression)
        {
            return UnitOfWork.GetIEnumerable<base_Department>(expression);
        }

        /// <summary>
        /// Get all base_Department.
        /// </summary>
        /// <returns>The new IQueryable&lt;base_Department&gt; instance.</returns>
        public IQueryable<base_Department> GetIQueryable()
        {
            return UnitOfWork.GetIQueryable<base_Department>();
        }

        /// <summary>
        /// Get all base_Department that satisfies a specified condition.
        /// </summary>
        /// <param name="expression">A function to test each base_Department for a condition.</param>
        /// <returns>The new IQueryable&lt;base_Department&gt; instance.</returns>
        public IQueryable<base_Department> GetIQueryable(Expression<Func<base_Department, bool>> expression)
        {
            return UnitOfWork.GetIQueryable<base_Department>(expression);
        }

        /// <summary>
        /// Take a few base_Department in a sequence was sorted on server.
        /// </summary>
        /// <param name="ignoreCount">Number of base_Department will ignore.</param>
        /// <param name="takeCount">Number of base_Department will take.</param>
        /// <param name="keys">The key columns by which to order the results.</param>
        /// <returns>The new IList&lt;base_Department&gt; instance.</returns>
        public IList<base_Department> GetRange(int ignoreCount, int takeCount, string keys)
        {
            return UnitOfWork.GetRange<base_Department>(ignoreCount, takeCount, keys);
        }

        /// <summary>
        /// Take a few base_Department in a sequence was sorted on server.
        /// </summary>
        /// <param name="ignoreCount">Number of base_Department will ignore.</param>
        /// <param name="takeCount">Number of base_Department will take.</param>
        /// <param name="keys">The key columns by which to order the results.</param>
        /// <param name="expression">A function to test each base_Department for a condition.</param>
        /// <returns>The new IList&lt;base_Department&gt; instance.</returns>
        public IList<base_Department> GetRange(int ignoreCount, int takeCount, string keys, Expression<Func<base_Department, bool>> expression)
        {
            return UnitOfWork.GetRange<base_Department>(ignoreCount, takeCount, keys, expression);
        }

        /// <summary>
        /// Take a few base_Department in sequence was sorted by descending on server.
        /// </summary>
        /// <typeparam name="TKey">Type of base_Department to sort</typeparam>
        /// <param name="ignoreCount">Number of base_Department will ignore.</param>
        /// <param name="takeCount">Number of base_Department will take.</param>
        /// <param name="keySelector">The key columns by which to order the results.</param>
        /// <returns>The new IList&lt;base_Department&gt; instance.</returns>
        public IList<base_Department> GetRangeDescending<TKey>(int ignoreCount, int takeCount, Expression<Func<base_Department, TKey>> keySelector)
        {
            return UnitOfWork.GetRangeDescending(ignoreCount, takeCount, keySelector);
        }

        /// <summary>
        /// Take a few base_Department in sequence was sorted by descending on server.
        /// </summary>
        /// <typeparam name="TKey">Type of base_Department to sort</typeparam>
        /// <param name="ignoreCount">Number of base_Department will ignore.</param>
        /// <param name="takeCount">Number of base_Department will take.</param>
        /// <param name="keySelector">The key columns by which to order the results.</param>
        /// <param name="expression">A function to test each object for a condition.</param>
        /// <returns>The new IList&lt;base_Department&gt; instance.</returns>
        public IList<base_Department> GetRangeDescending<TKey>(int ignoreCount, int takeCount, Expression<Func<base_Department, TKey>> keySelector, Expression<Func<base_Department, bool>> expression)
        {
            return UnitOfWork.GetRangeDescending(ignoreCount, takeCount, keySelector, expression);
        }

        /// <summary>
        /// Updates an base_Department in the object context with data from the data source.
        /// </summary>
        /// <param name="base_Department">The base_Department to be refreshed.</param>
        public base_Department Refresh(base_Department base_Department)
        {
            UnitOfWork.Refresh<base_Department>(base_Department);
            if (base_Department.EntityState != System.Data.EntityState.Detached)
                return base_Department;
            return null;
        }

        /// <summary>
        /// Updates a sequence of base_Department in the object context with data from the data source.
        /// </summary>
        /// <typeparam name="base_Department">Type of object in a sequence to refresh.</typeparam>
        /// <param name="base_Department">Object collection to be refreshed.</param>
        public void Refresh(IEnumerable<base_Department> base_Department)
        {
            UnitOfWork.Refresh<base_Department>(base_Department);
        }

        /// <summary>
        /// Updates a sequence of base_Department in the object context with data from the data source.
        /// </summary>
        public void Refresh()
        {
            UnitOfWork.Refresh<base_Department>();
        }

        /// <summary>
        /// Persists all updates to the data source and resets change tracking in the object context.
        /// </summary>
        public void Commit()
        {
            UnitOfWork.Commit();
        }

        /// <summary>
        /// Persists all updates to the data source with the specified System.Data.Objects.SaveOptions.
        /// </summary>
        /// <param name="options">A System.Data.Objects.SaveOptions value that determines the behavior of the operation.</param>
        public void Commit(SaveOptions options)
        {
            UnitOfWork.Commit(options);
        }

        /// <summary>
        /// Starts a database transaction.
        /// </summary>
        public void BeginTransaction()
        {
            UnitOfWork.BeginTransaction();
        }

        /// <summary>
        /// Commits the database transaction.
        /// </summary>
        public void CommitTransaction()
        {
            UnitOfWork.CommitTransaction();
        }

        /// <summary>
        /// Rolls back a transaction from a pending state.
        /// </summary>
        public void RollbackTransaction()
        {
            UnitOfWork.RollbackTransaction();
        }

        #endregion

        #endregion

        #region Custom Code


        #endregion
    }
}
