//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using CPC.Helper;
using CPC.POS.Database;
using CPC.Toolkit.Base;

namespace CPC.POS.Model
{
    /// <summary>
    /// Model for table rpt_Department
    /// </summary>
    [Serializable]
    public partial class rpt_DepartmentModel : ModelBase, IDataErrorInfo
    {
        #region Constructor

        // Default constructor
        public rpt_DepartmentModel()
        {
            this.IsNew = true;
            this.rpt_Department = new rpt_Department();
        }

        // Default constructor that set entity to field
        public rpt_DepartmentModel(rpt_Department rpt_department, bool isRaiseProperties = false)
        {
            this.rpt_Department = rpt_department;
            if (!isRaiseProperties)
                this.ToModel();
            else
                this.ToModelAndRaise();
            this.IsDirty = false;
        }

        #endregion

        #region Entity Properties

        public rpt_Department rpt_Department { get; private set; }

        #endregion

        #region Primitive Properties

        protected int _id;
        /// <summary>
        /// Property Model
        /// <param>Gets or sets the Id</param>
        /// </summary>
        public int Id
        {
            get { return this._id; }
            set
            {
                if (this._id != value)
                {
                    this.IsDirty = true;
                    this._id = value;
                    OnPropertyChanged(() => Id);
                    PropertyChangedCompleted(() => Id);
                }
            }
        }

        protected string _name;
        /// <summary>
        /// Property Model
        /// <param>Gets or sets the Name</param>
        /// </summary>
        public string Name
        {
            get { return this._name; }
            set
            {
                if (this._name != value)
                {
                    this.IsDirty = true;
                    this._name = value;
                    OnPropertyChanged(() => Name);
                    PropertyChangedCompleted(() => Name);
                }
            }
        }

        protected Nullable<short> _level;
        /// <summary>
        /// Property Model
        /// <param>Gets or sets the Level</param>
        /// </summary>
        public Nullable<short> Level
        {
            get { return this._level; }
            set
            {
                if (this._level != value)
                {
                    this.IsDirty = true;
                    this._level = value;
                    OnPropertyChanged(() => Level);
                    PropertyChangedCompleted(() => Level);
                }
            }
        }

        protected string _type;
        /// <summary>
        /// Property Model
        /// <param>Gets or sets the Type</param>
        /// </summary>
        public string Type
        {
            get { return this._type; }
            set
            {
                if (this._type != value)
                {
                    this.IsDirty = true;
                    this._type = value;
                    OnPropertyChanged(() => Type);
                    PropertyChangedCompleted(() => Type);
                }
            }
        }

        #endregion

        #region Public Methods

        /// <summary>
        /// <param>Public Method</param>
        /// Method for set IsNew & IsDirty = false;
        /// </summary>
        public void EndUpdate()
        {
            this.IsNew = false;
            this.IsDirty = false;
        }

        /// <summary>
        /// Public Method
        /// <param>Method for set PropertyModel to Entity</param>
        /// </summary>
        public void ToEntity()
        {
            if (IsNew)
                this.rpt_Department.Id = this.Id;
            if (this.Name != null)
                this.rpt_Department.Name = this.Name.Trim();
            this.rpt_Department.Level = this.Level;
            if (this.Type != null)
                this.rpt_Department.Type = this.Type.Trim();
        }

        /// <summary>
        /// Public Method
        /// <param>Method for set Entity to PropertyModel</param>
        /// </summary
        public void ToModel()
        {
            this._id = this.rpt_Department.Id;
            this._name = this.rpt_Department.Name;
            this._level = this.rpt_Department.Level;
            this._type = this.rpt_Department.Type;
        }

        /// <summary>
        /// Public Method
        /// <param>Method for set Entity to PropertyModel</param>
        /// </summary
        public void ToModelAndRaise()
        {
            this.Id = this.rpt_Department.Id;
            this.Name = this.rpt_Department.Name;
            this.Level = this.rpt_Department.Level;
            this.Type = this.rpt_Department.Type;
        }

        #endregion

        #region Custom Code


        #endregion

        #region IDataErrorInfo Members

        public string Error
        {
            get { throw new NotImplementedException(); }
        }

        public string this[string columnName]
        {
            get
            {
                string message = string.Empty;

                switch (columnName)
                {
                    case "Id":
                        break;
                    case "Name":
                        break;
                    case "Level":
                        break;
                    case "Type":
                        break;
                }

                if (!string.IsNullOrWhiteSpace(message))
                    return message;
                return null;
            }
        }

        #endregion
    }
}
