//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using CPC.POSReport.Database;
using Toolkit.Base;

namespace CPC.POSReport.Model
{
    /// <summary>
    /// Model for table base_GuestPaymentCard
    /// </summary>
    [Serializable]
    public partial class base_GuestPaymentCardModel : ModelBase, IDataErrorInfo
    {
        #region Constructor

        // Default constructor
        public base_GuestPaymentCardModel()
        {
            this.IsNew = true;
            this.base_GuestPaymentCard = new base_GuestPaymentCard();
        }

        // Default constructor that set entity to field
        public base_GuestPaymentCardModel(base_GuestPaymentCard base_guestpaymentcard, bool isRaiseProperties = false)
        {
            this.base_GuestPaymentCard = base_guestpaymentcard;
            if (!isRaiseProperties)
                this.ToModel();
            else
                this.ToModelAndRaise();
            this.IsDirty = false;
        }

        #endregion

        #region Entity Properties

        public base_GuestPaymentCard base_GuestPaymentCard { get; private set; }

        #endregion

        #region Primitive Properties

        protected int _id;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Id</para>
        /// </summary>
        public int Id
        {
            get { return this._id; }
            set
            {
                if (this._id != value)
                {
                    this.IsDirty = true;
                    this._id = value;
                    OnPropertyChanged(() => Id);
                    PropertyChangedCompleted(() => Id);
                }
            }
        }

        protected Nullable<long> _guestId;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the GuestId</para>
        /// </summary>
        public Nullable<long> GuestId
        {
            get { return this._guestId; }
            set
            {
                if (this._guestId != value)
                {
                    this.IsDirty = true;
                    this._guestId = value;
                    OnPropertyChanged(() => GuestId);
                    PropertyChangedCompleted(() => GuestId);
                }
            }
        }

        protected short _cardTypeId;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the CardTypeId</para>
        /// </summary>
        public short CardTypeId
        {
            get { return this._cardTypeId; }
            set
            {
                if (this._cardTypeId != value)
                {
                    this.IsDirty = true;
                    this._cardTypeId = value;
                    OnPropertyChanged(() => CardTypeId);
                    PropertyChangedCompleted(() => CardTypeId);
                }
            }
        }

        protected string _cardNumber;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the CardNumber</para>
        /// </summary>
        public string CardNumber
        {
            get { return this._cardNumber; }
            set
            {
                if (this._cardNumber != value)
                {
                    this.IsDirty = true;
                    this._cardNumber = value;
                    OnPropertyChanged(() => CardNumber);
                    PropertyChangedCompleted(() => CardNumber);
                }
            }
        }

        protected Nullable<short> _expMonth;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the ExpMonth</para>
        /// </summary>
        public Nullable<short> ExpMonth
        {
            get { return this._expMonth; }
            set
            {
                if (this._expMonth != value)
                {
                    this.IsDirty = true;
                    this._expMonth = value;
                    OnPropertyChanged(() => ExpMonth);
                    PropertyChangedCompleted(() => ExpMonth);
                }
            }
        }

        protected short _expYear;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the ExpYear</para>
        /// </summary>
        public short ExpYear
        {
            get { return this._expYear; }
            set
            {
                if (this._expYear != value)
                {
                    this.IsDirty = true;
                    this._expYear = value;
                    OnPropertyChanged(() => ExpYear);
                    PropertyChangedCompleted(() => ExpYear);
                }
            }
        }

        protected string _cCID;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the CCID</para>
        /// </summary>
        public string CCID
        {
            get { return this._cCID; }
            set
            {
                if (this._cCID != value)
                {
                    this.IsDirty = true;
                    this._cCID = value;
                    OnPropertyChanged(() => CCID);
                    PropertyChangedCompleted(() => CCID);
                }
            }
        }

        protected string _billingAddress;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the BillingAddress</para>
        /// </summary>
        public string BillingAddress
        {
            get { return this._billingAddress; }
            set
            {
                if (this._billingAddress != value)
                {
                    this.IsDirty = true;
                    this._billingAddress = value;
                    OnPropertyChanged(() => BillingAddress);
                    PropertyChangedCompleted(() => BillingAddress);
                }
            }
        }

        protected string _nameOnCard;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the NameOnCard</para>
        /// </summary>
        public string NameOnCard
        {
            get { return this._nameOnCard; }
            set
            {
                if (this._nameOnCard != value)
                {
                    this.IsDirty = true;
                    this._nameOnCard = value;
                    OnPropertyChanged(() => NameOnCard);
                    PropertyChangedCompleted(() => NameOnCard);
                }
            }
        }

        protected string _zipCode;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the ZipCode</para>
        /// </summary>
        public string ZipCode
        {
            get { return this._zipCode; }
            set
            {
                if (this._zipCode != value)
                {
                    this.IsDirty = true;
                    this._zipCode = value;
                    OnPropertyChanged(() => ZipCode);
                    PropertyChangedCompleted(() => ZipCode);
                }
            }
        }

        protected System.DateTime _dateCreated;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the DateCreated</para>
        /// </summary>
        public System.DateTime DateCreated
        {
            get { return this._dateCreated; }
            set
            {
                if (this._dateCreated != value)
                {
                    this.IsDirty = true;
                    this._dateCreated = value;
                    OnPropertyChanged(() => DateCreated);
                    PropertyChangedCompleted(() => DateCreated);
                }
            }
        }

        protected string _userCreated;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the UserCreated</para>
        /// </summary>
        public string UserCreated
        {
            get { return this._userCreated; }
            set
            {
                if (this._userCreated != value)
                {
                    this.IsDirty = true;
                    this._userCreated = value;
                    OnPropertyChanged(() => UserCreated);
                    PropertyChangedCompleted(() => UserCreated);
                }
            }
        }

        protected System.DateTime _dateUpdated;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the DateUpdated</para>
        /// </summary>
        public System.DateTime DateUpdated
        {
            get { return this._dateUpdated; }
            set
            {
                if (this._dateUpdated != value)
                {
                    this.IsDirty = true;
                    this._dateUpdated = value;
                    OnPropertyChanged(() => DateUpdated);
                    PropertyChangedCompleted(() => DateUpdated);
                }
            }
        }

        protected string _userUpdated;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the UserUpdated</para>
        /// </summary>
        public string UserUpdated
        {
            get { return this._userUpdated; }
            set
            {
                if (this._userUpdated != value)
                {
                    this.IsDirty = true;
                    this._userUpdated = value;
                    OnPropertyChanged(() => UserUpdated);
                    PropertyChangedCompleted(() => UserUpdated);
                }
            }
        }

        #endregion

        #region Public Methods

        /// <summary>
        /// <para>Public Method</para>
        /// Method for set IsNew & IsDirty = false;
        /// </summary>
        public void EndUpdate()
        {
            this.IsNew = false;
            this.IsDirty = false;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set PropertyModel to Entity</para>
        /// </summary>
        public void ToEntity()
        {
            if (IsNew)
                this.base_GuestPaymentCard.Id = this.Id;
            this.base_GuestPaymentCard.GuestId = this.GuestId;
            this.base_GuestPaymentCard.CardTypeId = this.CardTypeId;
            this.base_GuestPaymentCard.CardNumber = this.CardNumber;
            this.base_GuestPaymentCard.ExpMonth = this.ExpMonth;
            this.base_GuestPaymentCard.ExpYear = this.ExpYear;
            this.base_GuestPaymentCard.CCID = this.CCID;
            this.base_GuestPaymentCard.BillingAddress = this.BillingAddress;
            this.base_GuestPaymentCard.NameOnCard = this.NameOnCard;
            this.base_GuestPaymentCard.ZipCode = this.ZipCode;
            this.base_GuestPaymentCard.DateCreated = this.DateCreated;
            this.base_GuestPaymentCard.UserCreated = this.UserCreated;
            this.base_GuestPaymentCard.DateUpdated = this.DateUpdated;
            this.base_GuestPaymentCard.UserUpdated = this.UserUpdated;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set Entity to PropertyModel</para>
        /// </summary
        public void ToModel()
        {
            this._id = this.base_GuestPaymentCard.Id;
            this._guestId = this.base_GuestPaymentCard.GuestId;
            this._cardTypeId = this.base_GuestPaymentCard.CardTypeId;
            this._cardNumber = this.base_GuestPaymentCard.CardNumber;
            this._expMonth = this.base_GuestPaymentCard.ExpMonth;
            this._expYear = this.base_GuestPaymentCard.ExpYear;
            this._cCID = this.base_GuestPaymentCard.CCID;
            this._billingAddress = this.base_GuestPaymentCard.BillingAddress;
            this._nameOnCard = this.base_GuestPaymentCard.NameOnCard;
            this._zipCode = this.base_GuestPaymentCard.ZipCode;
            this._dateCreated = this.base_GuestPaymentCard.DateCreated;
            this._userCreated = this.base_GuestPaymentCard.UserCreated;
            this._dateUpdated = this.base_GuestPaymentCard.DateUpdated;
            this._userUpdated = this.base_GuestPaymentCard.UserUpdated;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set Entity to PropertyModel</para>
        /// </summary
        public void ToModelAndRaise()
        {
            this.Id = this.base_GuestPaymentCard.Id;
            this.GuestId = this.base_GuestPaymentCard.GuestId;
            this.CardTypeId = this.base_GuestPaymentCard.CardTypeId;
            this.CardNumber = this.base_GuestPaymentCard.CardNumber;
            this.ExpMonth = this.base_GuestPaymentCard.ExpMonth;
            this.ExpYear = this.base_GuestPaymentCard.ExpYear;
            this.CCID = this.base_GuestPaymentCard.CCID;
            this.BillingAddress = this.base_GuestPaymentCard.BillingAddress;
            this.NameOnCard = this.base_GuestPaymentCard.NameOnCard;
            this.ZipCode = this.base_GuestPaymentCard.ZipCode;
            this.DateCreated = this.base_GuestPaymentCard.DateCreated;
            this.UserCreated = this.base_GuestPaymentCard.UserCreated;
            this.DateUpdated = this.base_GuestPaymentCard.DateUpdated;
            this.UserUpdated = this.base_GuestPaymentCard.UserUpdated;
        }

        #endregion

        #region Custom Code


        #endregion

        #region IDataErrorInfo Members

        public string Error
        {
            get { throw new NotImplementedException(); }
        }

        public string this[string columnName]
        {
            get
            {
                string message = string.Empty;

                switch (columnName)
                {
                    case "Id":
                        break;
                    case "GuestId":
                        break;
                    case "CardTypeId":
                        break;
                    case "CardNumber":
                        break;
                    case "ExpMonth":
                        break;
                    case "ExpYear":
                        break;
                    case "CCID":
                        break;
                    case "BillingAddress":
                        break;
                    case "NameOnCard":
                        break;
                    case "ZipCode":
                        break;
                    case "DateCreated":
                        break;
                    case "UserCreated":
                        break;
                    case "DateUpdated":
                        break;
                    case "UserUpdated":
                        break;
                }

                if (!string.IsNullOrWhiteSpace(message))
                    return message;
                return null;
            }
        }

        #endregion
    }
}
