//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using CPC.POSReport.Database;
using Toolkit.Base;

namespace CPC.POSReport.Model
{
    /// <summary>
    /// Model for table base_SaleCommission
    /// </summary>
    [Serializable]
    public partial class base_SaleCommissionModel : ModelBase, IDataErrorInfo
    {
        #region Constructor

        // Default constructor
        public base_SaleCommissionModel()
        {
            this.IsNew = true;
            this.base_SaleCommission = new base_SaleCommission();
        }

        // Default constructor that set entity to field
        public base_SaleCommissionModel(base_SaleCommission base_salecommission, bool isRaiseProperties = false)
        {
            this.base_SaleCommission = base_salecommission;
            if (!isRaiseProperties)
                this.ToModel();
            else
                this.ToModelAndRaise();
            this.IsDirty = false;
        }

        #endregion

        #region Entity Properties

        public base_SaleCommission base_SaleCommission { get; private set; }

        #endregion

        #region Primitive Properties

        protected int _id;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Id</para>
        /// </summary>
        public int Id
        {
            get { return this._id; }
            set
            {
                if (this._id != value)
                {
                    this.IsDirty = true;
                    this._id = value;
                    OnPropertyChanged(() => Id);
                    PropertyChangedCompleted(() => Id);
                }
            }
        }

        protected string _guestResource;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the GuestResource</para>
        /// </summary>
        public string GuestResource
        {
            get { return this._guestResource; }
            set
            {
                if (this._guestResource != value)
                {
                    this.IsDirty = true;
                    this._guestResource = value;
                    OnPropertyChanged(() => GuestResource);
                    PropertyChangedCompleted(() => GuestResource);
                }
            }
        }

        protected string _sOResource;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the SOResource</para>
        /// </summary>
        public string SOResource
        {
            get { return this._sOResource; }
            set
            {
                if (this._sOResource != value)
                {
                    this.IsDirty = true;
                    this._sOResource = value;
                    OnPropertyChanged(() => SOResource);
                    PropertyChangedCompleted(() => SOResource);
                }
            }
        }

        protected string _sONumber;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the SONumber</para>
        /// </summary>
        public string SONumber
        {
            get { return this._sONumber; }
            set
            {
                if (this._sONumber != value)
                {
                    this.IsDirty = true;
                    this._sONumber = value;
                    OnPropertyChanged(() => SONumber);
                    PropertyChangedCompleted(() => SONumber);
                }
            }
        }

        protected Nullable<decimal> _sOTotal;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the SOTotal</para>
        /// </summary>
        public Nullable<decimal> SOTotal
        {
            get { return this._sOTotal; }
            set
            {
                if (this._sOTotal != value)
                {
                    this.IsDirty = true;
                    this._sOTotal = value;
                    OnPropertyChanged(() => SOTotal);
                    PropertyChangedCompleted(() => SOTotal);
                }
            }
        }

        protected Nullable<System.DateTime> _sODate;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the SODate</para>
        /// </summary>
        public Nullable<System.DateTime> SODate
        {
            get { return this._sODate; }
            set
            {
                if (this._sODate != value)
                {
                    this.IsDirty = true;
                    this._sODate = value;
                    OnPropertyChanged(() => SODate);
                    PropertyChangedCompleted(() => SODate);
                }
            }
        }

        protected string _saleOrderDetailResource;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the SaleOrderDetailResource</para>
        /// </summary>
        public string SaleOrderDetailResource
        {
            get { return this._saleOrderDetailResource; }
            set
            {
                if (this._saleOrderDetailResource != value)
                {
                    this.IsDirty = true;
                    this._saleOrderDetailResource = value;
                    OnPropertyChanged(() => SaleOrderDetailResource);
                    PropertyChangedCompleted(() => SaleOrderDetailResource);
                }
            }
        }

        protected string _productResource;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the ProductResource</para>
        /// </summary>
        public string ProductResource
        {
            get { return this._productResource; }
            set
            {
                if (this._productResource != value)
                {
                    this.IsDirty = true;
                    this._productResource = value;
                    OnPropertyChanged(() => ProductResource);
                    PropertyChangedCompleted(() => ProductResource);
                }
            }
        }

        protected string _attribute;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Attribute</para>
        /// </summary>
        public string Attribute
        {
            get { return this._attribute; }
            set
            {
                if (this._attribute != value)
                {
                    this.IsDirty = true;
                    this._attribute = value;
                    OnPropertyChanged(() => Attribute);
                    PropertyChangedCompleted(() => Attribute);
                }
            }
        }

        protected string _size;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Size</para>
        /// </summary>
        public string Size
        {
            get { return this._size; }
            set
            {
                if (this._size != value)
                {
                    this.IsDirty = true;
                    this._size = value;
                    OnPropertyChanged(() => Size);
                    PropertyChangedCompleted(() => Size);
                }
            }
        }

        protected Nullable<decimal> _quanity;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Quanity</para>
        /// </summary>
        public Nullable<decimal> Quanity
        {
            get { return this._quanity; }
            set
            {
                if (this._quanity != value)
                {
                    this.IsDirty = true;
                    this._quanity = value;
                    OnPropertyChanged(() => Quanity);
                    PropertyChangedCompleted(() => Quanity);
                }
            }
        }

        protected Nullable<decimal> _price;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Price</para>
        /// </summary>
        public Nullable<decimal> Price
        {
            get { return this._price; }
            set
            {
                if (this._price != value)
                {
                    this.IsDirty = true;
                    this._price = value;
                    OnPropertyChanged(() => Price);
                    PropertyChangedCompleted(() => Price);
                }
            }
        }

        protected Nullable<decimal> _amount;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Amount</para>
        /// </summary>
        public Nullable<decimal> Amount
        {
            get { return this._amount; }
            set
            {
                if (this._amount != value)
                {
                    this.IsDirty = true;
                    this._amount = value;
                    OnPropertyChanged(() => Amount);
                    PropertyChangedCompleted(() => Amount);
                }
            }
        }

        protected Nullable<decimal> _comissionPercent;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the ComissionPercent</para>
        /// </summary>
        public Nullable<decimal> ComissionPercent
        {
            get { return this._comissionPercent; }
            set
            {
                if (this._comissionPercent != value)
                {
                    this.IsDirty = true;
                    this._comissionPercent = value;
                    OnPropertyChanged(() => ComissionPercent);
                    PropertyChangedCompleted(() => ComissionPercent);
                }
            }
        }

        protected Nullable<decimal> _commissionAmount;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the CommissionAmount</para>
        /// </summary>
        public Nullable<decimal> CommissionAmount
        {
            get { return this._commissionAmount; }
            set
            {
                if (this._commissionAmount != value)
                {
                    this.IsDirty = true;
                    this._commissionAmount = value;
                    OnPropertyChanged(() => CommissionAmount);
                    PropertyChangedCompleted(() => CommissionAmount);
                }
            }
        }

        protected string _sign;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Sign</para>
        /// </summary>
        public string Sign
        {
            get { return this._sign; }
            set
            {
                if (this._sign != value)
                {
                    this.IsDirty = true;
                    this._sign = value;
                    OnPropertyChanged(() => Sign);
                    PropertyChangedCompleted(() => Sign);
                }
            }
        }

        protected string _remark;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Remark</para>
        /// </summary>
        public string Remark
        {
            get { return this._remark; }
            set
            {
                if (this._remark != value)
                {
                    this.IsDirty = true;
                    this._remark = value;
                    OnPropertyChanged(() => Remark);
                    PropertyChangedCompleted(() => Remark);
                }
            }
        }

        protected string _mark;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the Mark</para>
        /// </summary>
        public string Mark
        {
            get { return this._mark; }
            set
            {
                if (this._mark != value)
                {
                    this.IsDirty = true;
                    this._mark = value;
                    OnPropertyChanged(() => Mark);
                    PropertyChangedCompleted(() => Mark);
                }
            }
        }

        protected decimal _regularPrice;
        /// <summary>
        /// Property Model
        /// <para>Gets or sets the RegularPrice</para>
        /// </summary>
        public decimal RegularPrice
        {
            get { return this._regularPrice; }
            set
            {
                if (this._regularPrice != value)
                {
                    this.IsDirty = true;
                    this._regularPrice = value;
                    OnPropertyChanged(() => RegularPrice);
                    PropertyChangedCompleted(() => RegularPrice);
                }
            }
        }

        #endregion

        #region Public Methods

        /// <summary>
        /// <para>Public Method</para>
        /// Method for set IsNew & IsDirty = false;
        /// </summary>
        public void EndUpdate()
        {
            this.IsNew = false;
            this.IsDirty = false;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set PropertyModel to Entity</para>
        /// </summary>
        public void ToEntity()
        {
            if (IsNew)
                this.base_SaleCommission.Id = this.Id;
            this.base_SaleCommission.GuestResource = this.GuestResource;
            this.base_SaleCommission.SOResource = this.SOResource;
            this.base_SaleCommission.SONumber = this.SONumber;
            this.base_SaleCommission.SOTotal = this.SOTotal;
            this.base_SaleCommission.SODate = this.SODate;
            this.base_SaleCommission.SaleOrderDetailResource = this.SaleOrderDetailResource;
            this.base_SaleCommission.ProductResource = this.ProductResource;
            this.base_SaleCommission.Attribute = this.Attribute;
            this.base_SaleCommission.Size = this.Size;
            this.base_SaleCommission.Quanity = this.Quanity;
            this.base_SaleCommission.Price = this.Price;
            this.base_SaleCommission.Amount = this.Amount;
            this.base_SaleCommission.ComissionPercent = this.ComissionPercent;
            this.base_SaleCommission.CommissionAmount = this.CommissionAmount;
            this.base_SaleCommission.Sign = this.Sign;
            this.base_SaleCommission.Remark = this.Remark;
            this.base_SaleCommission.Mark = this.Mark;
            this.base_SaleCommission.RegularPrice = this.RegularPrice;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set Entity to PropertyModel</para>
        /// </summary
        public void ToModel()
        {
            this._id = this.base_SaleCommission.Id;
            this._guestResource = this.base_SaleCommission.GuestResource;
            this._sOResource = this.base_SaleCommission.SOResource;
            this._sONumber = this.base_SaleCommission.SONumber;
            this._sOTotal = this.base_SaleCommission.SOTotal;
            this._sODate = this.base_SaleCommission.SODate;
            this._saleOrderDetailResource = this.base_SaleCommission.SaleOrderDetailResource;
            this._productResource = this.base_SaleCommission.ProductResource;
            this._attribute = this.base_SaleCommission.Attribute;
            this._size = this.base_SaleCommission.Size;
            this._quanity = this.base_SaleCommission.Quanity;
            this._price = this.base_SaleCommission.Price;
            this._amount = this.base_SaleCommission.Amount;
            this._comissionPercent = this.base_SaleCommission.ComissionPercent;
            this._commissionAmount = this.base_SaleCommission.CommissionAmount;
            this._sign = this.base_SaleCommission.Sign;
            this._remark = this.base_SaleCommission.Remark;
            this._mark = this.base_SaleCommission.Mark;
            this._regularPrice = this.base_SaleCommission.RegularPrice;
        }

        /// <summary>
        /// Public Method
        /// <para>Method for set Entity to PropertyModel</para>
        /// </summary
        public void ToModelAndRaise()
        {
            this.Id = this.base_SaleCommission.Id;
            this.GuestResource = this.base_SaleCommission.GuestResource;
            this.SOResource = this.base_SaleCommission.SOResource;
            this.SONumber = this.base_SaleCommission.SONumber;
            this.SOTotal = this.base_SaleCommission.SOTotal;
            this.SODate = this.base_SaleCommission.SODate;
            this.SaleOrderDetailResource = this.base_SaleCommission.SaleOrderDetailResource;
            this.ProductResource = this.base_SaleCommission.ProductResource;
            this.Attribute = this.base_SaleCommission.Attribute;
            this.Size = this.base_SaleCommission.Size;
            this.Quanity = this.base_SaleCommission.Quanity;
            this.Price = this.base_SaleCommission.Price;
            this.Amount = this.base_SaleCommission.Amount;
            this.ComissionPercent = this.base_SaleCommission.ComissionPercent;
            this.CommissionAmount = this.base_SaleCommission.CommissionAmount;
            this.Sign = this.base_SaleCommission.Sign;
            this.Remark = this.base_SaleCommission.Remark;
            this.Mark = this.base_SaleCommission.Mark;
            this.RegularPrice = this.base_SaleCommission.RegularPrice;
        }

        #endregion

        #region Custom Code


        #endregion

        #region IDataErrorInfo Members

        public string Error
        {
            get { throw new NotImplementedException(); }
        }

        public string this[string columnName]
        {
            get
            {
                string message = string.Empty;

                switch (columnName)
                {
                    case "Id":
                        break;
                    case "GuestResource":
                        break;
                    case "SOResource":
                        break;
                    case "SONumber":
                        break;
                    case "SOTotal":
                        break;
                    case "SODate":
                        break;
                    case "ComissionPercent":
                        break;
                    case "CommissionAmount":
                        break;
                    case "Sign":
                        break;
                    case "Remark":
                        break;
                }

                if (!string.IsNullOrWhiteSpace(message))
                    return message;
                return null;
            }
        }

        #endregion
    }
}
