//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data.Objects;
using System.Linq;
using System.Linq.Expressions;
using CPC.POSReport.Database;

namespace CPC.POSReport.Repository
{
    /// <summary>
    /// Repository for table tims_WorkWeek 
    /// </summary>
    public partial class tims_WorkWeekRepository
    {
        #region Auto Generate Code

        #region Constructors

        // Default constructor
        public tims_WorkWeekRepository()
        {
        }

        #endregion

        #region Basic C.R.U.D. Operations

        /// <summary>
        /// Add new tims_WorkWeek.
        /// </summary>
        /// <param name="tims_WorkWeek">tims_WorkWeek to add.</param>
        /// <returns>tims_WorkWeek have been added.</returns>
        public tims_WorkWeek Add(tims_WorkWeek tims_WorkWeek)
        {
            UnitOfWork.Add<tims_WorkWeek>(tims_WorkWeek);
            return tims_WorkWeek;
        }

        /// <summary>
        /// Adds a sequence of new tims_WorkWeek.
        /// </summary>
        /// <param name="tims_WorkWeek">Sequence of new tims_WorkWeek to add.</param>
        /// <returns>Sequence of new tims_WorkWeek have been added.</returns>
        public IEnumerable<tims_WorkWeek> Add(IEnumerable<tims_WorkWeek> tims_WorkWeek)
        {
            UnitOfWork.Add<tims_WorkWeek>(tims_WorkWeek);
            return tims_WorkWeek;
        }

        /// <summary>
        /// Delete a existed tims_WorkWeek.
        /// </summary>
        /// <param name="tims_WorkWeek">tims_WorkWeek to delete.</param>
        public void Delete(tims_WorkWeek tims_WorkWeek)
        {
            Refresh(tims_WorkWeek);
            if (tims_WorkWeek.EntityState != System.Data.EntityState.Detached)
                UnitOfWork.Delete<tims_WorkWeek>(tims_WorkWeek);
        }

        /// <summary>
        /// Delete a sequence of existed tims_WorkWeek.
        /// </summary>
        /// <param name="tims_WorkWeek">Sequence of existed tims_WorkWeek to delete.</param>
        public void Delete(IEnumerable<tims_WorkWeek> tims_WorkWeek)
        {
            int total = tims_WorkWeek.Count();
            for (int i = total - 1; i >= 0; i--)
                Delete(tims_WorkWeek.ElementAt(i));
        }

        /// <summary>
        /// Returns the first tims_WorkWeek of a sequence that satisfies a specified condition or 
        /// a default value if no such tims_WorkWeek is found.
        /// </summary>
        /// <param name="expression">A function to test each tims_WorkWeek for a condition.</param>
        /// <returns>    
        /// Null if source is empty or if no tims_WorkWeek passes the test specified by expression; 
        /// otherwise, the first tims_WorkWeek in source that passes the test specified by expression.
        /// </returns>
        public tims_WorkWeek Get(Expression<Func<tims_WorkWeek, bool>> expression)
        {
            return UnitOfWork.Get<tims_WorkWeek>(expression);
        }

        /// <summary>
        /// Get all tims_WorkWeek.
        /// </summary>
        /// <returns>The new IList&lt;tims_WorkWeek&gt; instance.</returns>
        public IList<tims_WorkWeek> GetAll()
        {
            return UnitOfWork.GetAll<tims_WorkWeek>().ToList();
        }

        /// <summary>
        /// Get all tims_WorkWeek that satisfies a specified condition.
        /// </summary>
        /// <param name="expression">A function to test each tims_WorkWeek for a condition.</param>
        /// <returns>The new IList&lt;tims_WorkWeek&gt; instance.</returns>
        public IList<tims_WorkWeek> GetAll(Expression<Func<tims_WorkWeek, bool>> expression)
        {
            return UnitOfWork.GetAll<tims_WorkWeek>(expression).ToList();
        }

        /// <summary>
        /// Get all tims_WorkWeek.
        /// </summary>
        /// <returns>The new IEnumerable&lt;tims_WorkWeek&gt; instance.</returns>
        public IEnumerable<tims_WorkWeek> GetIEnumerable()
        {
            return UnitOfWork.GetIEnumerable<tims_WorkWeek>();
        }

        /// <summary>
        /// Get all tims_WorkWeek that satisfies a specified condition.
        /// </summary>
        /// <param name="expression">A function to test each tims_WorkWeek for a condition.</param>
        /// <returns>The new IEnumerable&lt;tims_WorkWeek&gt; instance.</returns>
        public IEnumerable<tims_WorkWeek> GetIEnumerable(Expression<Func<tims_WorkWeek, bool>> expression)
        {
            return UnitOfWork.GetIEnumerable<tims_WorkWeek>(expression);
        }

        /// <summary>
        /// Get all tims_WorkWeek.
        /// </summary>
        /// <returns>The new IQueryable&lt;tims_WorkWeek&gt; instance.</returns>
        public IQueryable<tims_WorkWeek> GetIQueryable()
        {
            return UnitOfWork.GetIQueryable<tims_WorkWeek>();
        }

        /// <summary>
        /// Get all tims_WorkWeek that satisfies a specified condition.
        /// </summary>
        /// <param name="expression">A function to test each tims_WorkWeek for a condition.</param>
        /// <returns>The new IQueryable&lt;tims_WorkWeek&gt; instance.</returns>
        public IQueryable<tims_WorkWeek> GetIQueryable(Expression<Func<tims_WorkWeek, bool>> expression)
        {
            return UnitOfWork.GetIQueryable<tims_WorkWeek>(expression);
        }

        /// <summary>
        /// Take a few tims_WorkWeek in a sequence was sorted on server.
        /// </summary>
        /// <param name="ignoreCount">Number of tims_WorkWeek will ignore.</param>
        /// <param name="takeCount">Number of tims_WorkWeek will take.</param>
        /// <param name="keys">The key columns by which to order the results.</param>
        /// <returns>The new IList&lt;tims_WorkWeek&gt; instance.</returns>
        public IList<tims_WorkWeek> GetRange(int ignoreCount, int takeCount, string keys)
        {
            return UnitOfWork.GetRange<tims_WorkWeek>(ignoreCount, takeCount, keys);
        }

        /// <summary>
        /// Take a few tims_WorkWeek in a sequence was sorted on server.
        /// </summary>
        /// <param name="ignoreCount">Number of tims_WorkWeek will ignore.</param>
        /// <param name="takeCount">Number of tims_WorkWeek will take.</param>
        /// <param name="keys">The key columns by which to order the results.</param>
        /// <param name="expression">A function to test each tims_WorkWeek for a condition.</param>
        /// <returns>The new IList&lt;tims_WorkWeek&gt; instance.</returns>
        public IList<tims_WorkWeek> GetRange(int ignoreCount, int takeCount, string keys, Expression<Func<tims_WorkWeek, bool>> expression)
        {
            return UnitOfWork.GetRange<tims_WorkWeek>(ignoreCount, takeCount, keys, expression);
        }

        /// <summary>
        /// Updates an tims_WorkWeek in the object context with data from the data source.
        /// </summary>
        /// <param name="tims_WorkWeek">The tims_WorkWeek to be refreshed.</param>
        public tims_WorkWeek Refresh(tims_WorkWeek tims_WorkWeek)
        {
            UnitOfWork.Refresh<tims_WorkWeek>(tims_WorkWeek);
            if (tims_WorkWeek.EntityState != System.Data.EntityState.Detached)
                return tims_WorkWeek;
            return null;
        }

        /// <summary>
        /// Updates a sequence of tims_WorkWeek in the object context with data from the data source.
        /// </summary>
        /// <typeparam name="tims_WorkWeek">Type of object in a sequence to refresh.</typeparam>
        /// <param name="tims_WorkWeek">Object collection to be refreshed.</param>
        public void Refresh(IEnumerable<tims_WorkWeek> tims_WorkWeek)
        {
            UnitOfWork.Refresh<tims_WorkWeek>(tims_WorkWeek);
        }

        /// <summary>
        /// Updates a sequence of tims_WorkWeek in the object context with data from the data source.
        /// </summary>
        public void Refresh()
        {
            UnitOfWork.Refresh<tims_WorkWeek>();
        }

        /// <summary>
        /// Persists all updates to the data source and resets change tracking in the object context.
        /// </summary>
        public void Commit()
        {
            UnitOfWork.Commit();
        }

        /// <summary>
        /// Persists all updates to the data source with the specified System.Data.Objects.SaveOptions.
        /// </summary>
        /// <param name="options">A System.Data.Objects.SaveOptions value that determines the behavior of the operation.</param>
        public void Commit(SaveOptions options)
        {
            UnitOfWork.Commit(options);
        }

        /// <summary>
        /// Starts a database transaction.
        /// </summary>
        public void BeginTransaction()
        {
            UnitOfWork.BeginTransaction();
        }

        /// <summary>
        /// Commits the database transaction.
        /// </summary>
        public void CommitTransaction()
        {
            UnitOfWork.CommitTransaction();
        }

        /// <summary>
        /// Rolls back a transaction from a pending state.
        /// </summary>
        public void RollbackTransaction()
        {
            UnitOfWork.RollbackTransaction();
        }

        #endregion

        #endregion

        #region Custom Code


        #endregion
    }
}
